// Emacs style mode select   -*- C++ -*- 
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// DESCRIPTION:
//	Thing frame/state LUT,
//	generated by multigen utilitiy.
//	This one is the original DOOM version, preserved.
//
//-----------------------------------------------------------------------------

#ifndef __INFO__
#define __INFO__

// Needed for action function pointer handling.
#include "d_think.h"

typedef enum
{
    SPR_TROO,
    SPR_SHTG,
    SPR_PUNG,
    SPR_PISG,
    SPR_PISF,
    SPR_SHTF,
    SPR_SHT2,
    SPR_CHGG,
    SPR_CHGF,
    SPR_MISG,
    SPR_MISF,
    SPR_SAWG,
    SPR_PLSG,
    SPR_PLSF,
    SPR_BFGG,
    SPR_BFGF,
    SPR_BLUD,
    SPR_PUFF,
    SPR_BAL1,
    SPR_BAL2,
    SPR_PLSS,
    SPR_PLSE,
    SPR_MISL,
    SPR_BFS1,
    SPR_BFE1,
    SPR_BFE2,
    SPR_TFOG,
    SPR_IFOG,
    SPR_PLAY,
    SPR_POSS,
    SPR_SPOS,
    SPR_VILE,
    SPR_FIRE,
    SPR_FATB,
    SPR_FBXP,
    SPR_SKEL,
    SPR_MANF,
    SPR_FATT,
    SPR_CPOS,
    SPR_SARG,
    SPR_HEAD,
    SPR_BAL7,
    SPR_BOSS,
    SPR_BOS2,
    SPR_SKUL,
    SPR_SPID,
    SPR_BSPI,
    SPR_APLS,
    SPR_APBX,
    SPR_CYBR,
    SPR_PAIN,
    SPR_SSWV,
    SPR_KEEN,
    SPR_BBRN,
    SPR_BOSF,
    SPR_ARM1,
    SPR_ARM2,
    SPR_BAR1,
    SPR_BEXP,
    SPR_FCAN,
    SPR_BON1,
    SPR_BON2,
    SPR_BKEY,
    SPR_RKEY,
    SPR_YKEY,
    SPR_BSKU,
    SPR_RSKU,
    SPR_YSKU,
    SPR_STIM,
    SPR_MEDI,
    SPR_SOUL,
    SPR_PINV,
    SPR_PSTR,
    SPR_PINS,
    SPR_MEGA,
    SPR_SUIT,
    SPR_PMAP,
    SPR_PVIS,
    SPR_CLIP,
    SPR_AMMO,
    SPR_ROCK,
    SPR_BROK,
    SPR_CELL,
    SPR_CELP,
    SPR_SHEL,
    SPR_SBOX,
    SPR_BPAK,
    SPR_BFUG,
    SPR_MGUN,
    SPR_CSAW,
    SPR_LAUN,
    SPR_PLAS,
    SPR_SHOT,
    SPR_SGN2,
    SPR_COLU,
    SPR_SMT2,
    SPR_GOR1,
    SPR_POL2,
    SPR_POL5,
    SPR_POL4,
    SPR_POL3,
    SPR_POL1,
    SPR_POL6,
    SPR_GOR2,
    SPR_GOR3,
    SPR_GOR4,
    SPR_GOR5,
    SPR_SMIT,
    SPR_COL1,
    SPR_COL2,
    SPR_COL3,
    SPR_COL4,
    SPR_CAND,
    SPR_CBRA,
    SPR_COL6,
    SPR_TRE1,
    SPR_TRE2,
    SPR_ELEC,
    SPR_CEYE,
    SPR_FSKU,
    SPR_COL5,
    SPR_TBLU,
    SPR_TGRN,
    SPR_TRED,
    SPR_SMBT,
    SPR_SMGT,
    SPR_SMRT,
    SPR_HDB1,
    SPR_HDB2,
    SPR_HDB3,
    SPR_HDB4,
    SPR_HDB5,
    SPR_HDB6,
    SPR_POB1,
    SPR_POB2,
    SPR_BRS1,
    SPR_TLMP,
    SPR_TLP2,
    // --- Heretic (additive; sprites come from hereticstuff.wad, renamed H*) ---
    SPR_HMUM,		// mummy / golem
    SPR_HCLK,		// sabreclaw (clink)
    SPR_HIMP,		// gargoyle (imp)
    SPR_HKNI,		// undead warrior (knight)
    SPR_HKAX,		// knight's thrown axe
    SPR_HBEA,		// weredragon (beast)
    SPR_HBEB,		// weredragon fireball
    SPR_HWIZ,		// disciple (wizard)
    SPR_HWIB,		// disciple fireball
    SPR_HSNK,		// ophidian (snake)
    SPR_HSNB,		// ophidian projectile
    SPR_HMIN,		// maulotaur (minotaur)
    SPR_HMNA,		// maulotaur mace ball
    SPR_HIRO,		// iron lich (head)
    SPR_HIRB,		// iron lich ice ball
    SPR_HIRX,		// iron lich whirlwind
    SPR_HSR2,		// d'sparil (phase-2 sorcerer)
    SPR_HSRB,		// d'sparil blue bolt
    // Freedoom DOOM2-exclusive monsters (renamed sprites from freedoomstuff.wad, so
    // they never collide with / override DOOM or doom2stuff).  See files/freedoom.c.
    SPR_FSKE,		// revenant      (doom2 SKEL)
    SPR_FFAT,		// mancubus      (FATT)
    SPR_FVIL,		// arch-vile     (VILE)
    SPR_FBSP,		// arachnotron   (BSPI)
    SPR_FCPO,		// chaingunner   (CPOS)
    SPR_FBO2,		// hell knight   (BOS2)
    SPR_FPAI,		// pain elemental(PAIN)
    SPR_FSSW,		// wolfenstein SS(SSWV)
    SPR_FKEE,		// commander keen(KEEN)
    SPR_FFAB,		// revenant tracer flight  (FATB)
    SPR_FFBX,		// revenant tracer explode (FBXP)
    SPR_FMAN,		// mancubus fireball       (MANF)
    SPR_FFIR,		// arch-vile fire          (FIRE)
    SPR_FAPL,		// arachnotron plasma      (APLS)
    SPR_FAPB,		// arachnotron plasma blast(APBX)
    // Hexen monsters (renamed sprites from hexenstuff.wad, X* namespace)
    SPR_XETT,		// ettin (XETT)
    SPR_XCEN,		// centaur / slaughtaur (XCEN)
    SPR_XCTF,		// slaughtaur reflective bolt (XCTF)
    SPR_XDEM,		// chaos serpent / demon (XDEM)
    SPR_XDMF,		// chaos serpent fireball (XDMF)
    SPR_XFDM,		// fire demon / afrit (XFDM)
    SPR_XFDB,		// fire demon fireball (XFDB)
    SPR_XWRT,		// reiver / wraith (XWRT)
    SPR_XWRB,		// reiver bolt (XWRB)
    SPR_XBIS,		// dark bishop (XBIS)
    SPR_XBPF,		// dark bishop missile (XBPF)
    SPR_XICE,		// wendigo / ice guy (XICE)
    SPR_XICP,		// wendigo ice-shard projectile (XICP)
    SPR_XSSP,		// stalker / serpent (XSSP)
    SPR_XSSF,		// stalker spit projectile (XSSF)
    SPR_XDRA,		// death wyvern / dragon (XDRA)
    SPR_XDRF,		// dragon fireball (XDRF)
    SPR_XMNT,		// minotaur / dark servant (XMNT)
    SPR_XFX1,		// minotaur mace ball (XFX1)
    SPR_XFX3,		// minotaur floor fire (XFX3)
    SPR_XMNS,		// minotaur teleport smoke (XMNS)
    SPR_XABA,		// korax bat (XABA)
    SPR_XPIG,		// pig -- Hexen morph creature (XPIG)
    SPR_XPLA,		// fighter class boss (XPLA -- Hexen PLAY)
    SPR_XCLE,		// cleric class boss (XCLE)
    SPR_XMAG,		// mage class boss (XMAG)
    SPR_XFSF,		// fighter boss Quietus bolt (XFSF)
    SPR_XSPI,		// cleric boss holy spirit (XSPI)
    SPR_XMS2,		// mage boss Bloodscourge shot (XMS2)
    // (H) Heretic artifact pickup sprites (hereticstuff.wad, 4-char Heretic codes).
    // MUST stay in lock-step with sprnames[] in info.c -- a mismatch shifts every
    // later sprite.  files/p_inv_heretic.c registers the pickup actors that use them.
    SPR_PTN1,		// Quartz Flask  (PTN1)
    SPR_SPHL,		// Mystic Urn    (SPHL)
    SPR_PWBK,		// Tome of Power (PWBK)
    SPR_TRCH,		// Torch         (TRCH)
    SPR_FBMB,		// Time Bomb     (FBMB)
    SPR_INVU,		// Ring of Invincibility (INVU)
    SPR_INVS,		// Shadowsphere  (INVS)
    SPR_ATLP,		// Chaos Device  (ATLP)
    SPR_SOAR,		// Wings of Wrath pickup (SOAR)
    SPR_EGGC,		// Morph Ovum pickup + egg projectile (EGGC)
    SPR_HCHK,		// morph chicken (HCHK) -- generic morph creature (files/p_morph.c)
    SPR_TNT1,		// invisible placeholder (no lumps) -- default for grown DSDHacked states
    SPR_MTUR,		// deployable sentry turret (MTUR*) -- patch lumps in run/ID0/buddydoom.wad
    SPR_MNDR,		// Security Drone body (MNDR*) -- from SecurityDrone.pk3, in buddydoom.wad
    SPR_SHT1,		// Security Drone laser shot (SHT1*)
    SPR_POW1,		// Security Drone laser impact (POW1*)
    SPR_XSSD,		// Hexen Serpent dive/submerge frames (XSSD*) -- from hexenstuff.wad
    SPR_PSBG,		// Hexen poison bag / poison cloud (PSBG*) -- from hexenstuff.wad (files/hexen.c)
    SPR_SHRM,		// Hexen poison shroom (SHRM*) -- destructible gas plant (files/hexen.c)
    // (H) Map-placeable Heretic item/pickup sprites (files/heretic_items.c).
    // Native 4-char Heretic codes registered directly in sprnames_builtin[]
    // (info.c) -- render straight out of heretic.wad in heretic_mode.
    SPR_HAKY,		// green key   (AKYY)
    SPR_HBKY,		// blue key    (BKYY)
    SPR_HCKY,		// yellow key  (CKYY)
    SPR_HAG1,		// gold wand ammo, wimpy (AMG1)
    SPR_HAG2,		// gold wand ammo, hefty (AMG2)
    SPR_HAM1,		// mace ammo, wimpy      (AMM1)
    SPR_HAM2,		// mace ammo, hefty      (AMM2)
    SPR_HAC1,		// crossbow ammo, wimpy  (AMC1)
    SPR_HAC2,		// crossbow ammo, hefty  (AMC2)
    SPR_HAS1,		// hellstaff ammo, wimpy (AMS1)
    SPR_HAS2,		// hellstaff ammo, hefty (AMS2)
    SPR_HAP1,		// phoenix ammo, wimpy   (AMP1)
    SPR_HAP2,		// phoenix ammo, hefty   (AMP2)
    SPR_HAB1,		// dragon-claw ammo, wimpy (AMB1)
    SPR_HAB2,		// dragon-claw ammo, hefty (AMB2)
    SPR_HWMC,		// firemace weapon       (WMCE)
    SPR_HWSK,		// hellstaff weapon      (WSKL)
    SPR_HWPH,		// phoenix rod weapon    (WPHX)
    SPR_HWBW,		// ethereal crossbow weapon (WBOW)
    SPR_HWGN,		// gauntlets weapon      (WGNT)
    SPR_HWBL,		// dragon claw weapon    (WBLS)
    SPR_HSHL,		// silver shield         (SHLD)
    SPR_HSH2,		// enchanted shield      (SHD2)
    // (H) Heretic decoration/scenery sprites (files/heretic_deco.c; H*->native remap)
    SPR_HPOD, SPR_HAMG, SPR_HSK1, SPR_HSK2, SPR_HSK3, SPR_HSK4, SPR_HCHD, SPR_HSRT,
    SPR_HSMP, SPR_HSGS, SPR_HSGL, SPR_HSCS, SPR_HSCL, SPR_HKFR, SPR_HBAR, SPR_HBRP,
    SPR_HMS1, SPR_HMS2, SPR_HWTR, SPR_HHCO, SPR_HKG1, SPR_HKGB, SPR_HKGG, SPR_HKGY,
    SPR_HVLC, SPR_HVFB, SPR_HVTF, SPR_HXPL, SPR_HSFF, SPR_HTGL, SPR_HTLE,
    // (H) Heretic monster-variant sprites (files/heretic_mvar.c; H*->native remap)
    SPR_HMUF, SPR_HKRX, SPR_HIMB, SPR_HSR1, SPR_HS1B,
    // (X) Hexen decoration/scenery sprites (files/hexen_deco.c; native codes, 5 aliased)
    SPR_ZBARL, SPR_ZBBLL, SPR_ZBCKT, SPR_ZBDPL, SPR_ZBDRP, SPR_ZBDSH,
    SPR_ZBNR1, SPR_ZBRTR, SPR_ZCAND, SPR_ZCDLR, SPR_ZCDRN, SPR_ZCHNS,
    SPR_ZCNDL, SPR_ZCPB1, SPR_ZCPB2, SPR_ZCPB3, SPR_ZCPB4, SPR_ZCPS1,
    SPR_ZCPS2, SPR_ZCPS3, SPR_ZCPS4, SPR_ZCPS5, SPR_ZCPS6, SPR_ZFBUL,
    SPR_ZFFLG, SPR_ZFFSM, SPR_ZFSKL, SPR_ZGAR1, SPR_ZGAR2, SPR_ZGAR3,
    SPR_ZGAR4, SPR_ZGAR5, SPR_ZGAR6, SPR_ZGAR7, SPR_ZGAR8, SPR_ZGAR9,
    SPR_ZICM1, SPR_ZICM2, SPR_ZICM3, SPR_ZICM4, SPR_ZICT1, SPR_ZICT2,
    SPR_ZICT3, SPR_ZICT4, SPR_ZIRON, SPR_ZLEF1, SPR_ZLEF2, SPR_ZLEF3,
    SPR_ZLOGG, SPR_ZMSH1, SPR_ZMSH2, SPR_ZMSH3, SPR_ZMSH4, SPR_ZMSH5,
    SPR_ZMSH6, SPR_ZMSH7, SPR_ZMSH8, SPR_ZMSS1, SPR_ZMSS2, SPR_ZPBIT,
    SPR_ZPOT1, SPR_ZPOT2, SPR_ZPOT3, SPR_ZRBL1, SPR_ZRBL2, SPR_ZRBL3,
    SPR_ZRCK1, SPR_ZRCK2, SPR_ZRCK3, SPR_ZRCK4, SPR_ZRKBK, SPR_ZRKBL,
    SPR_ZRKBS, SPR_ZROCK, SPR_ZSGM1, SPR_ZSGM2, SPR_ZSGM3, SPR_ZSGMP,
    SPR_ZSHB1, SPR_ZSHB2, SPR_ZSLC1, SPR_ZSLC2, SPR_ZSLC3, SPR_ZSTM1,
    SPR_ZSTM2, SPR_ZSTM3, SPR_ZSTM4, SPR_ZSTT2, SPR_ZSTT3, SPR_ZSTT4,
    SPR_ZSTT5, SPR_ZSTWN, SPR_ZSUIT, SPR_ZSWMV, SPR_ZTMS1, SPR_ZTMS2,
    SPR_ZTMS3, SPR_ZTMS4, SPR_ZTMS5, SPR_ZTMS6, SPR_ZTMS7, SPR_ZTRDT,
    SPR_ZTRE1, SPR_ZTRE2, SPR_ZTRE3, SPR_ZTRE4, SPR_ZTRE5, SPR_ZTRE6,
    SPR_ZTRE7, SPR_ZTSMK, SPR_ZTST0, SPR_ZTST1, SPR_ZTST2, SPR_ZTST3,
    SPR_ZTST4, SPR_ZTST5, SPR_ZTST6, SPR_ZTST7, SPR_ZTST8, SPR_ZTST9,
    SPR_ZTWTR, SPR_ZVASE, SPR_ZWLTR, SPR_ZXMAS,
    // (X) Hexen item/pickup/puzzle sprites (files/hexen_items.c; native codes)
    SPR_ZMAN1, SPR_ZMAN2, SPR_ZMAN3, SPR_ZARM3, SPR_ZARM4,
    SPR_ZKEY1, SPR_ZKEY2, SPR_ZKEY3, SPR_ZKEY4, SPR_ZKEY5, SPR_ZKEY6,
    SPR_ZKEY7, SPR_ZKEY8, SPR_ZKEY9, SPR_ZKEYA, SPR_ZKEYB,
    SPR_ZPTN2, SPR_ZTELO, SPR_ZSPED, SPR_ZBMAN, SPR_ZBRAC, SPR_ZBLST, SPR_ZHRAD,
    SPR_ZASKU, SPR_ZABGM, SPR_ZAGMR, SPR_ZAGMG, SPR_ZAGG2,
    SPR_ZAGMB, SPR_ZAGB2, SPR_ZABK1, SPR_ZABK2, SPR_ZASK2,
    SPR_ZAFWP, SPR_ZACWP, SPR_ZAMWP, SPR_ZAGER, SPR_ZAGR2, SPR_ZAGR3, SPR_ZAGR4,
    SPR_ZWFR1, SPR_ZWFR2, SPR_ZWFR3, SPR_ZWCH1, SPR_ZWCH2, SPR_ZWCH3,
    SPR_ZWMS1, SPR_ZWMS2, SPR_ZWMS3,
    // (X) Hexen monster/boss sprites (files/hexen_mon.c; native codes)
    SPR_XDEM2, SPR_XD2FX, SPR_XKORX, SPR_XMLFX, SPR_XSPIR,
    SPR_XSORC, SPR_XSBS1, SPR_XSBS2, SPR_XSBS3, SPR_XSBS4,
    // (H) Heretic weapon psprites + puffs (files/heretic_weapons.c)
    SPR_STFF, SPR_GWND, SPR_PUF3, SPR_PUF2,
    // (H) Heretic weapons phase 2-4: crossbow/blaster/hellstaff/phoenix/mace/gauntlets
    // psprites (CRBW/BLSR/HROD/PHNX/MACE/GAUN) + their projectiles/puffs (FX*/PUF1)
    SPR_CRBW, SPR_BLSR, SPR_HROD, SPR_PHNX, SPR_MACE, SPR_GAUN,
    SPR_FX03, SPR_FX17, SPR_FX00, SPR_FX04, SPR_FX08, SPR_FX02, SPR_PUF1,
    SPR_LICS, SPR_LICF, SPR_LICE,	// Lichling body / fire / ice (buddydoom.wad) -- buddy special
    SPR_HSPSH, SPR_HLVAS, SPR_HSLDG,	// (H) liquid-terrain splash: water / lava / sludge (heretic.wad)
    // (S) Strife sprite reservations (see strife_spr.inc, strife-ve order)
#include "strife_spr.inc"
    // (S) Strife Stalker buddy -- the art is SPID* in strife1.wad, but SPID is Doom's
    // Spider Mastermind (docs/BUDDY_SPRITE_COLLISIONS.md), so the buddy ships its own
    // STLK* frames in buddydoom.wad.  Appended AFTER the Strife block so the reserved
    // Strife sprite numbers stay put.
    SPR_STLK,
    NUMSPRITES

} spritenum_t;

typedef enum
{
    S_NULL,
    S_LIGHTDONE,
    S_PUNCH,
    S_PUNCHDOWN,
    S_PUNCHUP,
    S_PUNCH1,
    S_PUNCH2,
    S_PUNCH3,
    S_PUNCH4,
    S_PUNCH5,
    S_PISTOL,
    S_PISTOLDOWN,
    S_PISTOLUP,
    S_PISTOL1,
    S_PISTOL2,
    S_PISTOL3,
    S_PISTOL4,
    S_PISTOLFLASH,
    S_SGUN,
    S_SGUNDOWN,
    S_SGUNUP,
    S_SGUN1,
    S_SGUN2,
    S_SGUN3,
    S_SGUN4,
    S_SGUN5,
    S_SGUN6,
    S_SGUN7,
    S_SGUN8,
    S_SGUN9,
    S_SGUNFLASH1,
    S_SGUNFLASH2,
    S_DSGUN,
    S_DSGUNDOWN,
    S_DSGUNUP,
    S_DSGUN1,
    S_DSGUN2,
    S_DSGUN3,
    S_DSGUN4,
    S_DSGUN5,
    S_DSGUN6,
    S_DSGUN7,
    S_DSGUN8,
    S_DSGUN9,
    S_DSGUN10,
    S_DSNR1,
    S_DSNR2,
    S_DSGUNFLASH1,
    S_DSGUNFLASH2,
    S_CHAIN,
    S_CHAINDOWN,
    S_CHAINUP,
    S_CHAIN1,
    S_CHAIN2,
    S_CHAIN3,
    S_CHAINFLASH1,
    S_CHAINFLASH2,
    S_MISSILE,
    S_MISSILEDOWN,
    S_MISSILEUP,
    S_MISSILE1,
    S_MISSILE2,
    S_MISSILE3,
    S_MISSILEFLASH1,
    S_MISSILEFLASH2,
    S_MISSILEFLASH3,
    S_MISSILEFLASH4,
    S_SAW,
    S_SAWB,
    S_SAWDOWN,
    S_SAWUP,
    S_SAW1,
    S_SAW2,
    S_SAW3,
    S_PLASMA,
    S_PLASMADOWN,
    S_PLASMAUP,
    S_PLASMA1,
    S_PLASMA2,
    S_PLASMAFLASH1,
    S_PLASMAFLASH2,
    S_BFG,
    S_BFGDOWN,
    S_BFGUP,
    S_BFG1,
    S_BFG2,
    S_BFG3,
    S_BFG4,
    S_BFGFLASH1,
    S_BFGFLASH2,
    S_BLOOD1,
    S_BLOOD2,
    S_BLOOD3,
    S_PUFF1,
    S_PUFF2,
    S_PUFF3,
    S_PUFF4,
    S_TBALL1,
    S_TBALL2,
    S_TBALLX1,
    S_TBALLX2,
    S_TBALLX3,
    S_RBALL1,
    S_RBALL2,
    S_RBALLX1,
    S_RBALLX2,
    S_RBALLX3,
    S_PLASBALL,
    S_PLASBALL2,
    S_PLASEXP,
    S_PLASEXP2,
    S_PLASEXP3,
    S_PLASEXP4,
    S_PLASEXP5,
    S_ROCKET,
    S_BFGSHOT,
    S_BFGSHOT2,
    S_BFGLAND,
    S_BFGLAND2,
    S_BFGLAND3,
    S_BFGLAND4,
    S_BFGLAND5,
    S_BFGLAND6,
    S_BFGEXP,
    S_BFGEXP2,
    S_BFGEXP3,
    S_BFGEXP4,
    S_EXPLODE1,
    S_EXPLODE2,
    S_EXPLODE3,
    S_TFOG,
    S_TFOG01,
    S_TFOG02,
    S_TFOG2,
    S_TFOG3,
    S_TFOG4,
    S_TFOG5,
    S_TFOG6,
    S_TFOG7,
    S_TFOG8,
    S_TFOG9,
    S_TFOG10,
    S_IFOG,
    S_IFOG01,
    S_IFOG02,
    S_IFOG2,
    S_IFOG3,
    S_IFOG4,
    S_IFOG5,
    S_PLAY,
    S_PLAY_RUN1,
    S_PLAY_RUN2,
    S_PLAY_RUN3,
    S_PLAY_RUN4,
    S_PLAY_ATK1,
    S_PLAY_ATK2,
    S_PLAY_PAIN,
    S_PLAY_PAIN2,
    S_PLAY_DIE1,
    S_PLAY_DIE2,
    S_PLAY_DIE3,
    S_PLAY_DIE4,
    S_PLAY_DIE5,
    S_PLAY_DIE6,
    S_PLAY_DIE7,
    S_PLAY_XDIE1,
    S_PLAY_XDIE2,
    S_PLAY_XDIE3,
    S_PLAY_XDIE4,
    S_PLAY_XDIE5,
    S_PLAY_XDIE6,
    S_PLAY_XDIE7,
    S_PLAY_XDIE8,
    S_PLAY_XDIE9,
    S_POSS_STND,
    S_POSS_STND2,
    S_POSS_RUN1,
    S_POSS_RUN2,
    S_POSS_RUN3,
    S_POSS_RUN4,
    S_POSS_RUN5,
    S_POSS_RUN6,
    S_POSS_RUN7,
    S_POSS_RUN8,
    S_POSS_ATK1,
    S_POSS_ATK2,
    S_POSS_ATK3,
    S_POSS_PAIN,
    S_POSS_PAIN2,
    S_POSS_DIE1,
    S_POSS_DIE2,
    S_POSS_DIE3,
    S_POSS_DIE4,
    S_POSS_DIE5,
    S_POSS_XDIE1,
    S_POSS_XDIE2,
    S_POSS_XDIE3,
    S_POSS_XDIE4,
    S_POSS_XDIE5,
    S_POSS_XDIE6,
    S_POSS_XDIE7,
    S_POSS_XDIE8,
    S_POSS_XDIE9,
    S_POSS_RAISE1,
    S_POSS_RAISE2,
    S_POSS_RAISE3,
    S_POSS_RAISE4,
    S_SPOS_STND,
    S_SPOS_STND2,
    S_SPOS_RUN1,
    S_SPOS_RUN2,
    S_SPOS_RUN3,
    S_SPOS_RUN4,
    S_SPOS_RUN5,
    S_SPOS_RUN6,
    S_SPOS_RUN7,
    S_SPOS_RUN8,
    S_SPOS_ATK1,
    S_SPOS_ATK2,
    S_SPOS_ATK3,
    S_SPOS_PAIN,
    S_SPOS_PAIN2,
    S_SPOS_DIE1,
    S_SPOS_DIE2,
    S_SPOS_DIE3,
    S_SPOS_DIE4,
    S_SPOS_DIE5,
    S_SPOS_XDIE1,
    S_SPOS_XDIE2,
    S_SPOS_XDIE3,
    S_SPOS_XDIE4,
    S_SPOS_XDIE5,
    S_SPOS_XDIE6,
    S_SPOS_XDIE7,
    S_SPOS_XDIE8,
    S_SPOS_XDIE9,
    S_SPOS_RAISE1,
    S_SPOS_RAISE2,
    S_SPOS_RAISE3,
    S_SPOS_RAISE4,
    S_SPOS_RAISE5,
    S_VILE_STND,
    S_VILE_STND2,
    S_VILE_RUN1,
    S_VILE_RUN2,
    S_VILE_RUN3,
    S_VILE_RUN4,
    S_VILE_RUN5,
    S_VILE_RUN6,
    S_VILE_RUN7,
    S_VILE_RUN8,
    S_VILE_RUN9,
    S_VILE_RUN10,
    S_VILE_RUN11,
    S_VILE_RUN12,
    S_VILE_ATK1,
    S_VILE_ATK2,
    S_VILE_ATK3,
    S_VILE_ATK4,
    S_VILE_ATK5,
    S_VILE_ATK6,
    S_VILE_ATK7,
    S_VILE_ATK8,
    S_VILE_ATK9,
    S_VILE_ATK10,
    S_VILE_ATK11,
    S_VILE_HEAL1,
    S_VILE_HEAL2,
    S_VILE_HEAL3,
    S_VILE_PAIN,
    S_VILE_PAIN2,
    S_VILE_DIE1,
    S_VILE_DIE2,
    S_VILE_DIE3,
    S_VILE_DIE4,
    S_VILE_DIE5,
    S_VILE_DIE6,
    S_VILE_DIE7,
    S_VILE_DIE8,
    S_VILE_DIE9,
    S_VILE_DIE10,
    S_FIRE1,
    S_FIRE2,
    S_FIRE3,
    S_FIRE4,
    S_FIRE5,
    S_FIRE6,
    S_FIRE7,
    S_FIRE8,
    S_FIRE9,
    S_FIRE10,
    S_FIRE11,
    S_FIRE12,
    S_FIRE13,
    S_FIRE14,
    S_FIRE15,
    S_FIRE16,
    S_FIRE17,
    S_FIRE18,
    S_FIRE19,
    S_FIRE20,
    S_FIRE21,
    S_FIRE22,
    S_FIRE23,
    S_FIRE24,
    S_FIRE25,
    S_FIRE26,
    S_FIRE27,
    S_FIRE28,
    S_FIRE29,
    S_FIRE30,
    S_SMOKE1,
    S_SMOKE2,
    S_SMOKE3,
    S_SMOKE4,
    S_SMOKE5,
    S_TRACER,
    S_TRACER2,
    S_TRACEEXP1,
    S_TRACEEXP2,
    S_TRACEEXP3,
    S_SKEL_STND,
    S_SKEL_STND2,
    S_SKEL_RUN1,
    S_SKEL_RUN2,
    S_SKEL_RUN3,
    S_SKEL_RUN4,
    S_SKEL_RUN5,
    S_SKEL_RUN6,
    S_SKEL_RUN7,
    S_SKEL_RUN8,
    S_SKEL_RUN9,
    S_SKEL_RUN10,
    S_SKEL_RUN11,
    S_SKEL_RUN12,
    S_SKEL_FIST1,
    S_SKEL_FIST2,
    S_SKEL_FIST3,
    S_SKEL_FIST4,
    S_SKEL_MISS1,
    S_SKEL_MISS2,
    S_SKEL_MISS3,
    S_SKEL_MISS4,
    S_SKEL_PAIN,
    S_SKEL_PAIN2,
    S_SKEL_DIE1,
    S_SKEL_DIE2,
    S_SKEL_DIE3,
    S_SKEL_DIE4,
    S_SKEL_DIE5,
    S_SKEL_DIE6,
    S_SKEL_RAISE1,
    S_SKEL_RAISE2,
    S_SKEL_RAISE3,
    S_SKEL_RAISE4,
    S_SKEL_RAISE5,
    S_SKEL_RAISE6,
    S_FATSHOT1,
    S_FATSHOT2,
    S_FATSHOTX1,
    S_FATSHOTX2,
    S_FATSHOTX3,
    S_FATT_STND,
    S_FATT_STND2,
    S_FATT_RUN1,
    S_FATT_RUN2,
    S_FATT_RUN3,
    S_FATT_RUN4,
    S_FATT_RUN5,
    S_FATT_RUN6,
    S_FATT_RUN7,
    S_FATT_RUN8,
    S_FATT_RUN9,
    S_FATT_RUN10,
    S_FATT_RUN11,
    S_FATT_RUN12,
    S_FATT_ATK1,
    S_FATT_ATK2,
    S_FATT_ATK3,
    S_FATT_ATK4,
    S_FATT_ATK5,
    S_FATT_ATK6,
    S_FATT_ATK7,
    S_FATT_ATK8,
    S_FATT_ATK9,
    S_FATT_ATK10,
    S_FATT_PAIN,
    S_FATT_PAIN2,
    S_FATT_DIE1,
    S_FATT_DIE2,
    S_FATT_DIE3,
    S_FATT_DIE4,
    S_FATT_DIE5,
    S_FATT_DIE6,
    S_FATT_DIE7,
    S_FATT_DIE8,
    S_FATT_DIE9,
    S_FATT_DIE10,
    S_FATT_RAISE1,
    S_FATT_RAISE2,
    S_FATT_RAISE3,
    S_FATT_RAISE4,
    S_FATT_RAISE5,
    S_FATT_RAISE6,
    S_FATT_RAISE7,
    S_FATT_RAISE8,
    S_CPOS_STND,
    S_CPOS_STND2,
    S_CPOS_RUN1,
    S_CPOS_RUN2,
    S_CPOS_RUN3,
    S_CPOS_RUN4,
    S_CPOS_RUN5,
    S_CPOS_RUN6,
    S_CPOS_RUN7,
    S_CPOS_RUN8,
    S_CPOS_ATK1,
    S_CPOS_ATK2,
    S_CPOS_ATK3,
    S_CPOS_ATK4,
    S_CPOS_PAIN,
    S_CPOS_PAIN2,
    S_CPOS_DIE1,
    S_CPOS_DIE2,
    S_CPOS_DIE3,
    S_CPOS_DIE4,
    S_CPOS_DIE5,
    S_CPOS_DIE6,
    S_CPOS_DIE7,
    S_CPOS_XDIE1,
    S_CPOS_XDIE2,
    S_CPOS_XDIE3,
    S_CPOS_XDIE4,
    S_CPOS_XDIE5,
    S_CPOS_XDIE6,
    S_CPOS_RAISE1,
    S_CPOS_RAISE2,
    S_CPOS_RAISE3,
    S_CPOS_RAISE4,
    S_CPOS_RAISE5,
    S_CPOS_RAISE6,
    S_CPOS_RAISE7,
    S_TROO_STND,
    S_TROO_STND2,
    S_TROO_RUN1,
    S_TROO_RUN2,
    S_TROO_RUN3,
    S_TROO_RUN4,
    S_TROO_RUN5,
    S_TROO_RUN6,
    S_TROO_RUN7,
    S_TROO_RUN8,
    S_TROO_ATK1,
    S_TROO_ATK2,
    S_TROO_ATK3,
    S_TROO_PAIN,
    S_TROO_PAIN2,
    S_TROO_DIE1,
    S_TROO_DIE2,
    S_TROO_DIE3,
    S_TROO_DIE4,
    S_TROO_DIE5,
    S_TROO_XDIE1,
    S_TROO_XDIE2,
    S_TROO_XDIE3,
    S_TROO_XDIE4,
    S_TROO_XDIE5,
    S_TROO_XDIE6,
    S_TROO_XDIE7,
    S_TROO_XDIE8,
    S_TROO_RAISE1,
    S_TROO_RAISE2,
    S_TROO_RAISE3,
    S_TROO_RAISE4,
    S_TROO_RAISE5,
    S_SARG_STND,
    S_SARG_STND2,
    S_SARG_RUN1,
    S_SARG_RUN2,
    S_SARG_RUN3,
    S_SARG_RUN4,
    S_SARG_RUN5,
    S_SARG_RUN6,
    S_SARG_RUN7,
    S_SARG_RUN8,
    S_SARG_ATK1,
    S_SARG_ATK2,
    S_SARG_ATK3,
    S_SARG_PAIN,
    S_SARG_PAIN2,
    S_SARG_DIE1,
    S_SARG_DIE2,
    S_SARG_DIE3,
    S_SARG_DIE4,
    S_SARG_DIE5,
    S_SARG_DIE6,
    S_SARG_RAISE1,
    S_SARG_RAISE2,
    S_SARG_RAISE3,
    S_SARG_RAISE4,
    S_SARG_RAISE5,
    S_SARG_RAISE6,
    S_HEAD_STND,
    S_HEAD_RUN1,
    S_HEAD_ATK1,
    S_HEAD_ATK2,
    S_HEAD_ATK3,
    S_HEAD_PAIN,
    S_HEAD_PAIN2,
    S_HEAD_PAIN3,
    S_HEAD_DIE1,
    S_HEAD_DIE2,
    S_HEAD_DIE3,
    S_HEAD_DIE4,
    S_HEAD_DIE5,
    S_HEAD_DIE6,
    S_HEAD_RAISE1,
    S_HEAD_RAISE2,
    S_HEAD_RAISE3,
    S_HEAD_RAISE4,
    S_HEAD_RAISE5,
    S_HEAD_RAISE6,
    S_BRBALL1,
    S_BRBALL2,
    S_BRBALLX1,
    S_BRBALLX2,
    S_BRBALLX3,
    S_BOSS_STND,
    S_BOSS_STND2,
    S_BOSS_RUN1,
    S_BOSS_RUN2,
    S_BOSS_RUN3,
    S_BOSS_RUN4,
    S_BOSS_RUN5,
    S_BOSS_RUN6,
    S_BOSS_RUN7,
    S_BOSS_RUN8,
    S_BOSS_ATK1,
    S_BOSS_ATK2,
    S_BOSS_ATK3,
    S_BOSS_PAIN,
    S_BOSS_PAIN2,
    S_BOSS_DIE1,
    S_BOSS_DIE2,
    S_BOSS_DIE3,
    S_BOSS_DIE4,
    S_BOSS_DIE5,
    S_BOSS_DIE6,
    S_BOSS_DIE7,
    S_BOSS_RAISE1,
    S_BOSS_RAISE2,
    S_BOSS_RAISE3,
    S_BOSS_RAISE4,
    S_BOSS_RAISE5,
    S_BOSS_RAISE6,
    S_BOSS_RAISE7,
    S_BOS2_STND,
    S_BOS2_STND2,
    S_BOS2_RUN1,
    S_BOS2_RUN2,
    S_BOS2_RUN3,
    S_BOS2_RUN4,
    S_BOS2_RUN5,
    S_BOS2_RUN6,
    S_BOS2_RUN7,
    S_BOS2_RUN8,
    S_BOS2_ATK1,
    S_BOS2_ATK2,
    S_BOS2_ATK3,
    S_BOS2_PAIN,
    S_BOS2_PAIN2,
    S_BOS2_DIE1,
    S_BOS2_DIE2,
    S_BOS2_DIE3,
    S_BOS2_DIE4,
    S_BOS2_DIE5,
    S_BOS2_DIE6,
    S_BOS2_DIE7,
    S_BOS2_RAISE1,
    S_BOS2_RAISE2,
    S_BOS2_RAISE3,
    S_BOS2_RAISE4,
    S_BOS2_RAISE5,
    S_BOS2_RAISE6,
    S_BOS2_RAISE7,
    S_SKULL_STND,
    S_SKULL_STND2,
    S_SKULL_RUN1,
    S_SKULL_RUN2,
    S_SKULL_ATK1,
    S_SKULL_ATK2,
    S_SKULL_ATK3,
    S_SKULL_ATK4,
    S_SKULL_PAIN,
    S_SKULL_PAIN2,
    S_SKULL_DIE1,
    S_SKULL_DIE2,
    S_SKULL_DIE3,
    S_SKULL_DIE4,
    S_SKULL_DIE5,
    S_SKULL_DIE6,
    S_SPID_STND,
    S_SPID_STND2,
    S_SPID_RUN1,
    S_SPID_RUN2,
    S_SPID_RUN3,
    S_SPID_RUN4,
    S_SPID_RUN5,
    S_SPID_RUN6,
    S_SPID_RUN7,
    S_SPID_RUN8,
    S_SPID_RUN9,
    S_SPID_RUN10,
    S_SPID_RUN11,
    S_SPID_RUN12,
    S_SPID_ATK1,
    S_SPID_ATK2,
    S_SPID_ATK3,
    S_SPID_ATK4,
    S_SPID_PAIN,
    S_SPID_PAIN2,
    S_SPID_DIE1,
    S_SPID_DIE2,
    S_SPID_DIE3,
    S_SPID_DIE4,
    S_SPID_DIE5,
    S_SPID_DIE6,
    S_SPID_DIE7,
    S_SPID_DIE8,
    S_SPID_DIE9,
    S_SPID_DIE10,
    S_SPID_DIE11,
    S_BSPI_STND,
    S_BSPI_STND2,
    S_BSPI_SIGHT,
    S_BSPI_RUN1,
    S_BSPI_RUN2,
    S_BSPI_RUN3,
    S_BSPI_RUN4,
    S_BSPI_RUN5,
    S_BSPI_RUN6,
    S_BSPI_RUN7,
    S_BSPI_RUN8,
    S_BSPI_RUN9,
    S_BSPI_RUN10,
    S_BSPI_RUN11,
    S_BSPI_RUN12,
    S_BSPI_ATK1,
    S_BSPI_ATK2,
    S_BSPI_ATK3,
    S_BSPI_ATK4,
    S_BSPI_PAIN,
    S_BSPI_PAIN2,
    S_BSPI_DIE1,
    S_BSPI_DIE2,
    S_BSPI_DIE3,
    S_BSPI_DIE4,
    S_BSPI_DIE5,
    S_BSPI_DIE6,
    S_BSPI_DIE7,
    S_BSPI_RAISE1,
    S_BSPI_RAISE2,
    S_BSPI_RAISE3,
    S_BSPI_RAISE4,
    S_BSPI_RAISE5,
    S_BSPI_RAISE6,
    S_BSPI_RAISE7,
    S_ARACH_PLAZ,
    S_ARACH_PLAZ2,
    S_ARACH_PLEX,
    S_ARACH_PLEX2,
    S_ARACH_PLEX3,
    S_ARACH_PLEX4,
    S_ARACH_PLEX5,
    S_CYBER_STND,
    S_CYBER_STND2,
    S_CYBER_RUN1,
    S_CYBER_RUN2,
    S_CYBER_RUN3,
    S_CYBER_RUN4,
    S_CYBER_RUN5,
    S_CYBER_RUN6,
    S_CYBER_RUN7,
    S_CYBER_RUN8,
    S_CYBER_ATK1,
    S_CYBER_ATK2,
    S_CYBER_ATK3,
    S_CYBER_ATK4,
    S_CYBER_ATK5,
    S_CYBER_ATK6,
    S_CYBER_PAIN,
    S_CYBER_DIE1,
    S_CYBER_DIE2,
    S_CYBER_DIE3,
    S_CYBER_DIE4,
    S_CYBER_DIE5,
    S_CYBER_DIE6,
    S_CYBER_DIE7,
    S_CYBER_DIE8,
    S_CYBER_DIE9,
    S_CYBER_DIE10,
    S_PAIN_STND,
    S_PAIN_RUN1,
    S_PAIN_RUN2,
    S_PAIN_RUN3,
    S_PAIN_RUN4,
    S_PAIN_RUN5,
    S_PAIN_RUN6,
    S_PAIN_ATK1,
    S_PAIN_ATK2,
    S_PAIN_ATK3,
    S_PAIN_ATK4,
    S_PAIN_PAIN,
    S_PAIN_PAIN2,
    S_PAIN_DIE1,
    S_PAIN_DIE2,
    S_PAIN_DIE3,
    S_PAIN_DIE4,
    S_PAIN_DIE5,
    S_PAIN_DIE6,
    S_PAIN_RAISE1,
    S_PAIN_RAISE2,
    S_PAIN_RAISE3,
    S_PAIN_RAISE4,
    S_PAIN_RAISE5,
    S_PAIN_RAISE6,
    S_SSWV_STND,
    S_SSWV_STND2,
    S_SSWV_RUN1,
    S_SSWV_RUN2,
    S_SSWV_RUN3,
    S_SSWV_RUN4,
    S_SSWV_RUN5,
    S_SSWV_RUN6,
    S_SSWV_RUN7,
    S_SSWV_RUN8,
    S_SSWV_ATK1,
    S_SSWV_ATK2,
    S_SSWV_ATK3,
    S_SSWV_ATK4,
    S_SSWV_ATK5,
    S_SSWV_ATK6,
    S_SSWV_PAIN,
    S_SSWV_PAIN2,
    S_SSWV_DIE1,
    S_SSWV_DIE2,
    S_SSWV_DIE3,
    S_SSWV_DIE4,
    S_SSWV_DIE5,
    S_SSWV_XDIE1,
    S_SSWV_XDIE2,
    S_SSWV_XDIE3,
    S_SSWV_XDIE4,
    S_SSWV_XDIE5,
    S_SSWV_XDIE6,
    S_SSWV_XDIE7,
    S_SSWV_XDIE8,
    S_SSWV_XDIE9,
    S_SSWV_RAISE1,
    S_SSWV_RAISE2,
    S_SSWV_RAISE3,
    S_SSWV_RAISE4,
    S_SSWV_RAISE5,
    S_KEENSTND,
    S_COMMKEEN,
    S_COMMKEEN2,
    S_COMMKEEN3,
    S_COMMKEEN4,
    S_COMMKEEN5,
    S_COMMKEEN6,
    S_COMMKEEN7,
    S_COMMKEEN8,
    S_COMMKEEN9,
    S_COMMKEEN10,
    S_COMMKEEN11,
    S_COMMKEEN12,
    S_KEENPAIN,
    S_KEENPAIN2,
    S_BRAIN,
    S_BRAIN_PAIN,
    S_BRAIN_DIE1,
    S_BRAIN_DIE2,
    S_BRAIN_DIE3,
    S_BRAIN_DIE4,
    S_BRAINEYE,
    S_BRAINEYESEE,
    S_BRAINEYE1,
    S_SPAWN1,
    S_SPAWN2,
    S_SPAWN3,
    S_SPAWN4,
    S_SPAWNFIRE1,
    S_SPAWNFIRE2,
    S_SPAWNFIRE3,
    S_SPAWNFIRE4,
    S_SPAWNFIRE5,
    S_SPAWNFIRE6,
    S_SPAWNFIRE7,
    S_SPAWNFIRE8,
    S_BRAINEXPLODE1,
    S_BRAINEXPLODE2,
    S_BRAINEXPLODE3,
    S_ARM1,
    S_ARM1A,
    S_ARM2,
    S_ARM2A,
    S_BAR1,
    S_BAR2,
    S_BEXP,
    S_BEXP2,
    S_BEXP3,
    S_BEXP4,
    S_BEXP5,
    S_BBAR1,
    S_BBAR2,
    S_BBAR3,
    S_BON1,
    S_BON1A,
    S_BON1B,
    S_BON1C,
    S_BON1D,
    S_BON1E,
    S_BON2,
    S_BON2A,
    S_BON2B,
    S_BON2C,
    S_BON2D,
    S_BON2E,
    S_BKEY,
    S_BKEY2,
    S_RKEY,
    S_RKEY2,
    S_YKEY,
    S_YKEY2,
    S_BSKULL,
    S_BSKULL2,
    S_RSKULL,
    S_RSKULL2,
    S_YSKULL,
    S_YSKULL2,
    S_STIM,
    S_MEDI,
    S_SOUL,
    S_SOUL2,
    S_SOUL3,
    S_SOUL4,
    S_SOUL5,
    S_SOUL6,
    S_PINV,
    S_PINV2,
    S_PINV3,
    S_PINV4,
    S_PSTR,
    S_PINS,
    S_PINS2,
    S_PINS3,
    S_PINS4,
    S_MEGA,
    S_MEGA2,
    S_MEGA3,
    S_MEGA4,
    S_SUIT,
    S_PMAP,
    S_PMAP2,
    S_PMAP3,
    S_PMAP4,
    S_PMAP5,
    S_PMAP6,
    S_PVIS,
    S_PVIS2,
    S_CLIP,
    S_AMMO,
    S_ROCK,
    S_BROK,
    S_CELL,
    S_CELP,
    S_SHEL,
    S_SBOX,
    S_BPAK,
    S_BFUG,
    S_MGUN,
    S_CSAW,
    S_LAUN,
    S_PLAS,
    S_SHOT,
    S_SHOT2,
    S_COLU,
    S_STALAG,
    S_BLOODYTWITCH,
    S_BLOODYTWITCH2,
    S_BLOODYTWITCH3,
    S_BLOODYTWITCH4,
    S_DEADTORSO,
    S_DEADBOTTOM,
    S_HEADSONSTICK,
    S_GIBS,
    S_HEADONASTICK,
    S_HEADCANDLES,
    S_HEADCANDLES2,
    S_DEADSTICK,
    S_LIVESTICK,
    S_LIVESTICK2,
    S_MEAT2,
    S_MEAT3,
    S_MEAT4,
    S_MEAT5,
    S_STALAGTITE,
    S_TALLGRNCOL,
    S_SHRTGRNCOL,
    S_TALLREDCOL,
    S_SHRTREDCOL,
    S_CANDLESTIK,
    S_CANDELABRA,
    S_SKULLCOL,
    S_TORCHTREE,
    S_BIGTREE,
    S_TECHPILLAR,
    S_EVILEYE,
    S_EVILEYE2,
    S_EVILEYE3,
    S_EVILEYE4,
    S_FLOATSKULL,
    S_FLOATSKULL2,
    S_FLOATSKULL3,
    S_HEARTCOL,
    S_HEARTCOL2,
    S_BLUETORCH,
    S_BLUETORCH2,
    S_BLUETORCH3,
    S_BLUETORCH4,
    S_GREENTORCH,
    S_GREENTORCH2,
    S_GREENTORCH3,
    S_GREENTORCH4,
    S_REDTORCH,
    S_REDTORCH2,
    S_REDTORCH3,
    S_REDTORCH4,
    S_BTORCHSHRT,
    S_BTORCHSHRT2,
    S_BTORCHSHRT3,
    S_BTORCHSHRT4,
    S_GTORCHSHRT,
    S_GTORCHSHRT2,
    S_GTORCHSHRT3,
    S_GTORCHSHRT4,
    S_RTORCHSHRT,
    S_RTORCHSHRT2,
    S_RTORCHSHRT3,
    S_RTORCHSHRT4,
    S_HANGNOGUTS,
    S_HANGBNOBRAIN,
    S_HANGTLOOKDN,
    S_HANGTSKULL,
    S_HANGTLOOKUP,
    S_HANGTNOBRAIN,
    S_COLONGIBS,
    S_SMALLPOOL,
    S_BRAINSTEM,
    S_TECHLAMP,
    S_TECHLAMP2,
    S_TECHLAMP3,
    S_TECHLAMP4,
    S_TECH2LAMP,
    S_TECH2LAMP2,
    S_TECH2LAMP3,
    S_TECH2LAMP4,
    // === BuddyDoom appended actor states RELOCATED to a high base ==============
    // Everything below (Heretic/Hexen/Freedoom/turret/drone/... states) is BuddyDoom's
    // own additions.  DSDHacked WADs (Legacy of Rust defines frames 1100-1566) share
    // this state-index space; if our builtins sat there, a partial LoR "Frame N ="
    // edit (which only sets sprite/tics/next, NOT the sprite subnumber) would inherit
    // OUR leftover subnumber -> the Ghoul idled on GHUL frame 'N' (a dissolve frame,
    // the "green ring") instead of 'A'.  Basing the block at 4000 leaves 967..3999 a
    // clean/empty slate so LoR's partial frame edits get proper defaults (subnumber 0).
    // The built-in table is sparse across the gap, but dsdhacked.c memcpy's it whole.
    // --- Heretic mummy (filled at runtime by Heretic_Init in heretic.c) ---
    S_HMUM_LOOK1 = 4000, S_HMUM_LOOK2,
    S_HMUM_WALK1, S_HMUM_WALK2, S_HMUM_WALK3, S_HMUM_WALK4,
    S_HMUM_ATK1,  S_HMUM_ATK2,  S_HMUM_ATK3,
    S_HMUM_PAIN1, S_HMUM_PAIN2,
    S_HMUM_DIE1,  S_HMUM_DIE2,  S_HMUM_DIE3,  S_HMUM_DIE4,
    S_HMUM_DIE5,  S_HMUM_DIE6,  S_HMUM_DIE7,  S_HMUM_DIE8,
    // Heretic sabreclaw (clink)
    S_HCLK_LOOK1, S_HCLK_LOOK2,
    S_HCLK_WALK1, S_HCLK_WALK2, S_HCLK_WALK3, S_HCLK_WALK4,
    S_HCLK_ATK1,  S_HCLK_ATK2,  S_HCLK_ATK3,
    S_HCLK_PAIN1, S_HCLK_PAIN2,
    S_HCLK_DIE1,  S_HCLK_DIE2,  S_HCLK_DIE3,  S_HCLK_DIE4,
    S_HCLK_DIE5,  S_HCLK_DIE6,  S_HCLK_DIE7,
    // Heretic gargoyle (imp) -- flies, melee + skull-fly charge
    S_HIMP_LOOK1, S_HIMP_LOOK2, S_HIMP_LOOK3, S_HIMP_LOOK4,
    S_HIMP_FLY1,  S_HIMP_FLY2,  S_HIMP_FLY3,  S_HIMP_FLY4,
    S_HIMP_FLY5,  S_HIMP_FLY6,  S_HIMP_FLY7,  S_HIMP_FLY8,
    S_HIMP_MEATK1,S_HIMP_MEATK2,S_HIMP_MEATK3,
    S_HIMP_MSATK1,S_HIMP_MSATK2,S_HIMP_MSATK3,
    S_HIMP_MSATK4,S_HIMP_MSATK5,S_HIMP_MSATK6,
    S_HIMP_PAIN1, S_HIMP_PAIN2,
    S_HIMP_DIE1,  S_HIMP_DIE2,			// fall (frames 6,7)
    S_HIMP_DIE3,  S_HIMP_DIE4,  S_HIMP_DIE5, S_HIMP_DIE6,	// crash (frames 8..11)
    // undead warrior (knight): STND, WALK, ATK (melee or throw axe), PAIN, DIE
    S_HKNI_STND1, S_HKNI_STND2,
    S_HKNI_WALK1, S_HKNI_WALK2, S_HKNI_WALK3, S_HKNI_WALK4,
    S_HKNI_ATK1,  S_HKNI_ATK2,  S_HKNI_ATK3,  S_HKNI_ATK4, S_HKNI_ATK5, S_HKNI_ATK6,
    S_HKNI_PAIN1, S_HKNI_PAIN2,
    S_HKNI_DIE1,  S_HKNI_DIE2,  S_HKNI_DIE3,  S_HKNI_DIE4, S_HKNI_DIE5, S_HKNI_DIE6, S_HKNI_DIE7,
    // knight's thrown axe projectile: spin (3) + explode (3)
    S_HKAX1, S_HKAX2, S_HKAX3,
    S_HKAXX1, S_HKAXX2, S_HKAXX3,
    // ---- Weredragon (beast) + fireball ----
    S_HBEA_LOOK1, S_HBEA_LOOK2,
    S_HBEA_WALK1, S_HBEA_WALK2, S_HBEA_WALK3, S_HBEA_WALK4, S_HBEA_WALK5, S_HBEA_WALK6,
    S_HBEA_ATK1, S_HBEA_ATK2,
    S_HBEA_PAIN1, S_HBEA_PAIN2,
    S_HBEA_DIE1, S_HBEA_DIE2, S_HBEA_DIE3, S_HBEA_DIE4, S_HBEA_DIE5, S_HBEA_DIE6, S_HBEA_DIE7, S_HBEA_DIE8, S_HBEA_DIE9,
    S_HBEB1, S_HBEB2, S_HBEB3, S_HBEB4, S_HBEB5, S_HBEB6,
    S_HBEBX1, S_HBEBX2, S_HBEBX3, S_HBEBX4, S_HBEBX5,
    // ---- Disciple (wizard) + fireball ----
    S_HWIZ_LOOK1, S_HWIZ_LOOK2,
    S_HWIZ_WALK1, S_HWIZ_WALK2, S_HWIZ_WALK3, S_HWIZ_WALK4, S_HWIZ_WALK5, S_HWIZ_WALK6, S_HWIZ_WALK7, S_HWIZ_WALK8,
    S_HWIZ_ATK1, S_HWIZ_ATK2, S_HWIZ_ATK3,
    S_HWIZ_PAIN1, S_HWIZ_PAIN2,
    S_HWIZ_DIE1, S_HWIZ_DIE2, S_HWIZ_DIE3, S_HWIZ_DIE4, S_HWIZ_DIE5, S_HWIZ_DIE6, S_HWIZ_DIE7, S_HWIZ_DIE8,
    S_HWIB1, S_HWIB2,
    S_HWIBX1, S_HWIBX2, S_HWIBX3, S_HWIBX4, S_HWIBX5,
    // ---- Ophidian (snake) + projectile ----
    S_HSNK_LOOK1, S_HSNK_LOOK2,
    S_HSNK_WALK1, S_HSNK_WALK2, S_HSNK_WALK3, S_HSNK_WALK4,
    S_HSNK_ATK1, S_HSNK_ATK2, S_HSNK_ATK3, S_HSNK_ATK4, S_HSNK_ATK5,
    S_HSNK_PAIN1, S_HSNK_PAIN2,
    S_HSNK_DIE1, S_HSNK_DIE2, S_HSNK_DIE3, S_HSNK_DIE4, S_HSNK_DIE5, S_HSNK_DIE6, S_HSNK_DIE7, S_HSNK_DIE8, S_HSNK_DIE9, S_HSNK_DIE10,
    S_HSNB1, S_HSNB2, S_HSNB3, S_HSNB4,
    S_HSNBX1, S_HSNBX2, S_HSNBX3, S_HSNBX4, S_HSNBX5,
    // ---- Maulotaur (minotaur) + mace ball ----
    S_HMIN_LOOK1, S_HMIN_LOOK2,
    S_HMIN_WALK1, S_HMIN_WALK2, S_HMIN_WALK3, S_HMIN_WALK4,
    S_HMIN_ATK1_1, S_HMIN_ATK1_2, S_HMIN_ATK1_3,
    S_HMIN_ATK2_1, S_HMIN_ATK2_2, S_HMIN_ATK2_3,
    S_HMIN_ATK4_1,
    S_HMIN_PAIN1, S_HMIN_PAIN2,
    S_HMIN_DIE1, S_HMIN_DIE2, S_HMIN_DIE3, S_HMIN_DIE4, S_HMIN_DIE5, S_HMIN_DIE6, S_HMIN_DIE7, S_HMIN_DIE8,
    S_HMIN_DIE9, S_HMIN_DIE10, S_HMIN_DIE11, S_HMIN_DIE12, S_HMIN_DIE13, S_HMIN_DIE14, S_HMIN_DIE15,
    S_HMNA1, S_HMNA2,
    S_HMNAX1, S_HMNAX2, S_HMNAX3, S_HMNAX4, S_HMNAX5, S_HMNAX6,
    // ---- Iron Lich (head) + ice ball + homing whirlwind ----
    S_HIRO_LOOK, S_HIRO_FLOAT,
    S_HIRO_ATK1, S_HIRO_ATK2,
    S_HIRO_PAIN1, S_HIRO_PAIN2,
    S_HIRO_DIE1, S_HIRO_DIE2, S_HIRO_DIE3, S_HIRO_DIE4, S_HIRO_DIE5, S_HIRO_DIE6, S_HIRO_DIE7,
    S_HIRB1, S_HIRB2, S_HIRB3,
    S_HIRBX1, S_HIRBX2, S_HIRBX3, S_HIRBX4,
    S_HIRX1, S_HIRX2, S_HIRX3, S_HIRX4, S_HIRX5, S_HIRX6, S_HIRX7,
    S_HIRXX1, S_HIRXX2,
    // ---- D'Sparil (phase-2 sorcerer) + blue bolt ----
    S_HSR2_LOOK1, S_HSR2_LOOK2,
    S_HSR2_WALK1, S_HSR2_WALK2, S_HSR2_WALK3, S_HSR2_WALK4,
    S_HSR2_ATK1, S_HSR2_ATK2, S_HSR2_ATK3,
    S_HSR2_PAIN1, S_HSR2_PAIN2,
    S_HSR2_DIE1, S_HSR2_DIE2, S_HSR2_DIE3, S_HSR2_DIE4, S_HSR2_DIE5, S_HSR2_DIE6,
    S_HSRB1, S_HSRB2, S_HSRB3,
    S_HSRBX1, S_HSRBX2, S_HSRBX3, S_HSRBX4, S_HSRBX5, S_HSRBX6,
    // Freedoom: a reserved block of state slots that freedoom.c fills at runtime by
    // CLONING each DOOM2 monster's state graph (with the sprite remapped).  512 covers
    // ~9 monsters + 4 projectiles (~340 states) with headroom.  See files/freedoom.c.
    S_FD_FIRST,
    S_FD_LAST = S_FD_FIRST + 511,
    // ---- Hexen monsters (filled at runtime by Hexen_Init) ----
    S_XETT_LOOK1, S_XETT_LOOK2,
    S_XETT_CHASE1, S_XETT_CHASE2, S_XETT_CHASE3, S_XETT_CHASE4,
    S_XETT_PAIN1,
    S_XETT_ATK1, S_XETT_ATK2, S_XETT_ATK3,
    S_XETT_DIE1, S_XETT_DIE2, S_XETT_DIE3, S_XETT_DIE4, S_XETT_DIE5,
    S_XETT_DIE6, S_XETT_DIE7, S_XETT_DIE8, S_XETT_DIE9,
    // Centaur / Slaughtaur (melee brute; the leader also lobs a bolt)
    S_XCEN_LOOK1, S_XCEN_LOOK2,
    S_XCEN_WALK1, S_XCEN_WALK2, S_XCEN_WALK3, S_XCEN_WALK4,
    S_XCEN_ATK1, S_XCEN_ATK2, S_XCEN_ATK3,
    S_XCEN_MIS1, S_XCEN_MIS2, S_XCEN_MIS3, S_XCEN_MIS4,
    S_XCEN_PAIN1, S_XCEN_PAIN2,
    S_XCEN_DIE1, S_XCEN_DIE2, S_XCEN_DIE3, S_XCEN_DIE4, S_XCEN_DIE5,
    S_XCEN_DIE6, S_XCEN_DIE7, S_XCEN_DIE8, S_XCEN_DIE9, S_XCEN_DIE10,
    // Slaughtaur reflective bolt projectile
    S_XCTF_MOVE1,
    S_XCTF_X1, S_XCTF_X2, S_XCTF_X3, S_XCTF_X4, S_XCTF_X5,
    // Chaos Serpent / Demon (melee + fire-breath fireball)
    S_XDEM_LOOK1, S_XDEM_LOOK2,
    S_XDEM_CHASE1, S_XDEM_CHASE2, S_XDEM_CHASE3, S_XDEM_CHASE4,
    S_XDEM_ATK1_1, S_XDEM_ATK1_2, S_XDEM_ATK1_3,
    S_XDEM_ATK2_1, S_XDEM_ATK2_2, S_XDEM_ATK2_3,
    S_XDEM_PAIN1, S_XDEM_PAIN2,
    S_XDEM_DIE1, S_XDEM_DIE2, S_XDEM_DIE3, S_XDEM_DIE4, S_XDEM_DIE5,
    S_XDEM_DIE6, S_XDEM_DIE7, S_XDEM_DIE8, S_XDEM_DIE9,
    // Chaos Serpent fireball projectile
    S_XDMF_MOVE1, S_XDMF_MOVE2, S_XDMF_MOVE3,
    S_XDMF_BOOM1, S_XDMF_BOOM2, S_XDMF_BOOM3, S_XDMF_BOOM4, S_XDMF_BOOM5,
    // Fire Demon / Afrit (flying; lobs fireballs -- ranged only)
    S_XFDM_LOOK1, S_XFDM_LOOK2, S_XFDM_LOOK3,
    S_XFDM_WALK1, S_XFDM_WALK2, S_XFDM_WALK3,
    S_XFDM_ATK1, S_XFDM_ATK2, S_XFDM_ATK3, S_XFDM_ATK4,
    S_XFDM_PAIN1,
    S_XFDM_DIE1, S_XFDM_DIE2, S_XFDM_DIE3, S_XFDM_DIE4,
    S_XFDM_DIE5, S_XFDM_DIE6, S_XFDM_DIE7,
    // Afrit death splotches: the two scorch marks thrown out by the final burst
    S_XFDS_DROP1, S_XFDS_LAND1, S_XFDS_REST1,
    S_XFDS_DROP2, S_XFDS_LAND2, S_XFDS_REST2,
    // Fire Demon fireball projectile
    S_XFDB_MOVE1, S_XFDB_MOVE2, S_XFDB_MOVE3,
    S_XFDB_BOOM1, S_XFDB_BOOM2, S_XFDB_BOOM3, S_XFDB_BOOM4, S_XFDB_BOOM5,
    // Reiver / Wraith (floating; melee + ranged bolt)
    S_XWRT_LOOK1, S_XWRT_LOOK2,
    S_XWRT_CHASE1, S_XWRT_CHASE2, S_XWRT_CHASE3, S_XWRT_CHASE4,
    S_XWRT_ATK1_1, S_XWRT_ATK1_2, S_XWRT_ATK1_3,
    S_XWRT_ATK2_1, S_XWRT_ATK2_2, S_XWRT_ATK2_3,
    S_XWRT_PAIN1, S_XWRT_PAIN2,
    S_XWRT_DIE1, S_XWRT_DIE2, S_XWRT_DIE3, S_XWRT_DIE4, S_XWRT_DIE5,
    S_XWRT_DIE6, S_XWRT_DIE7, S_XWRT_DIE8, S_XWRT_DIE9, S_XWRT_DIE10,
    // Reiver bolt projectile
    S_XWRB_MOVE1, S_XWRB_MOVE2, S_XWRB_MOVE3,
    S_XWRB_BOOM1, S_XWRB_BOOM2, S_XWRB_BOOM3, S_XWRB_BOOM4, S_XWRB_BOOM5, S_XWRB_BOOM6,
    // Dark Bishop (floating caster; melee + ranged missile -- homing/blur simplified away)
    S_XBIS_LOOK1,
    S_XBIS_WALK1, S_XBIS_WALK2, S_XBIS_WALK3,
    S_XBIS_ATK1, S_XBIS_ATK2, S_XBIS_ATK3, S_XBIS_ATK4, S_XBIS_ATK5,
    S_XBIS_PAIN1,
    S_XBIS_DIE1, S_XBIS_DIE2, S_XBIS_DIE3, S_XBIS_DIE4, S_XBIS_DIE5,
    S_XBIS_DIE6, S_XBIS_DIE7,
    // Dark Bishop missile projectile
    S_XBPF_MOVE1, S_XBPF_MOVE2,
    S_XBPF_BOOM1, S_XBPF_BOOM2, S_XBPF_BOOM3, S_XBPF_BOOM4, S_XBPF_BOOM5,
    // Wendigo / Ice Guy (ranged ice-shard caster; wisps/bits/dual-shot simplified away)
    S_XICE_LOOK1, S_XICE_LOOK2,
    S_XICE_WALK1, S_XICE_WALK2, S_XICE_WALK3, S_XICE_WALK4,
    S_XICE_ATK1, S_XICE_ATK2, S_XICE_ATK3, S_XICE_ATK4,
    S_XICE_PAIN1,
    S_XICE_DIE1, S_XICE_DIE2, S_XICE_DIE3,
    // Wendigo ice-shard projectile
    S_XICP_MOVE1, S_XICP_MOVE2, S_XICP_MOVE3,
    S_XICP_BOOM1, S_XICP_BOOM2, S_XICP_BOOM3, S_XICP_BOOM4, S_XICP_BOOM5,
    // Stalker / Serpent (authentic ZDoom ritual: submerged invisible+invulnerable chaser,
    // humps to telegraph, surfaces to attack (then vulnerable), dives back under).
    S_XSSP_LOOK1, S_XSSP_LOOK2,
    S_XSSP_SEE1, S_XSSP_SEE2,				// invisible underwater chase
    S_XSSP_HUMP1, S_XSSP_HUMP2, S_XSSP_HUMP3, S_XSSP_HUMP4,	// telegraph bump (visible, still invulnerable)
    S_XSSP_SURF1, S_XSSP_SURF2,				// surface for attack (become visible + shootable)
    S_XSSD_DIVE1, S_XSSD_DIVE2, S_XSSD_DIVE3, S_XSSD_DIVE4,	// dive back under (XSSD sprite)
    S_XSSP_WALK1, S_XSSP_WALK2, S_XSSP_WALK3, S_XSSP_WALK4,
    S_XSSP_ATK1, S_XSSP_ATK2, S_XSSP_MEL1, S_XSSP_MIS1,
    S_XSSP_PAIN1, S_XSSP_PAIN2,
    S_XSSP_DIE1, S_XSSP_DIE2, S_XSSP_DIE3, S_XSSP_DIE4, S_XSSP_DIE5,
    S_XSSP_DIE6, S_XSSP_DIE7, S_XSSP_DIE8, S_XSSP_DIE9,
    S_XSSP_DIE10, S_XSSP_DIE11, S_XSSP_DIE12,	// full 12-frame serpent death (crispy)
    // Stalker spit projectile
    S_XSSF_MOVE1, S_XSSF_MOVE2, S_XSSF_MOVE3, S_XSSF_MOVE4,
    S_XSSF_BOOM1, S_XSSF_BOOM2, S_XSSF_BOOM3, S_XSSF_BOOM4, S_XSSF_BOOM5, S_XSSF_BOOM6,
    // Death Wyvern / Dragon (big flying ranged boss; flight ritual/crash simplified away)
    S_XDRA_LOOK1, S_XDRA_LOOK2,
    S_XDRA_WALK1, S_XDRA_WALK2, S_XDRA_WALK3, S_XDRA_WALK4,
    S_XDRA_ATK1,
    S_XDRA_PAIN1,
    S_XDRA_DIE1, S_XDRA_DIE2, S_XDRA_DIE3, S_XDRA_DIE4, S_XDRA_DIE5,
    // Dragon fireball projectile
    S_XDRF_MOVE1, S_XDRF_MOVE2, S_XDRF_MOVE3, S_XDRF_MOVE4, S_XDRF_MOVE5, S_XDRF_MOVE6,
    S_XDRF_BOOM1, S_XDRF_BOOM2, S_XDRF_BOOM3, S_XDRF_BOOM4, S_XDRF_BOOM5, S_XDRF_BOOM6,
    // (G) revived friendly marine -- PLAY sprite, zombieman-style AI (files/revmarine.c)
    S_REVMAR_STND,
    S_REVMAR_RUN1, S_REVMAR_RUN2, S_REVMAR_RUN3, S_REVMAR_RUN4,
    S_REVMAR_ATK1, S_REVMAR_ATK2,
    S_REVMAR_PAIN,
    S_REVMAR_DIE1, S_REVMAR_DIE2, S_REVMAR_DIE3, S_REVMAR_DIE4,
    S_REVMAR_DIE5, S_REVMAR_DIE6, S_REVMAR_DIE7,
    // (G) "get up" -- the death frames played in REVERSE when a corpse is revived
    S_REVMAR_RISE1, S_REVMAR_RISE2, S_REVMAR_RISE3, S_REVMAR_RISE4,
    S_REVMAR_RISE5, S_REVMAR_RISE6, S_REVMAR_RISE7,
    // (H) Heretic artifact pickup spinning-icon states (files/p_inv_heretic.c).
    // One spawnstate per artifact (looping); filled in HereticInv_Init.
    S_HARTI_FLASK, S_HARTI_URN, S_HARTI_TOME, S_HARTI_TORCH,
    S_HARTI_BOMB,  S_HARTI_RING, S_HARTI_SHADOW, S_HARTI_CHAOS,
    // (H) Time Bomb of the Ancients actor: fuse frames then A_Explode (reusing the
    // DOOM barrel-blast sprite SPR_BEXP for the boom, since SPR_XPL1 isn't extracted).
    S_HFIREBOMB1, S_HFIREBOMB2, S_HFIREBOMB3, S_HFIREBOMB4, S_HFIREBOMB5,
    S_HFIREBOMB6, S_HFIREBOMB7, S_HFIREBOMB8, S_HFIREBOMB9, S_HFIREBOMB10,
    // (H) Wings of Wrath + Morph Ovum pickup spinning-icon states (p_inv_heretic.c).
    S_HARTI_WINGS, S_HARTI_EGG,
    // Egg projectile (MT_HEGGFX) flight states (files/p_inv_heretic.c).
    S_HEGGFX1, S_HEGGFX2, S_HEGGFX3, S_HEGGFX4, S_HEGGFX5,
    // (M) generic morph creature -- the Heretic chicken (files/p_morph.c).
    S_CHIC_LOOK1, S_CHIC_LOOK2,
    S_CHIC_WALK1, S_CHIC_WALK2,
    S_CHIC_ATK1, S_CHIC_ATK2,
    S_CHIC_PAIN1, S_CHIC_PAIN2,
    S_CHIC_DIE1, S_CHIC_DIE2, S_CHIC_DIE3, S_CHIC_DIE4, S_CHIC_DIE5,
    // Boom push/pull point-source (MT_PUSH/MT_PULL) idle state: invisible + persistent.
    S_TNT1,
    // Deployable sentry turret (files/p_turret.c): idle look loop, fire loop, death boom.
    // (Sits inside the relocated 4000+ block above, clear of the DSDHacked frame range.)
    S_TURRET_STND,
    S_TURRET_FIRE1, S_TURRET_FIRE2,
    S_TURRET_DIE1, S_TURRET_DIE2, S_TURRET_DIE3, S_TURRET_DIE4, S_TURRET_DIE5,
    // Security Drone (files/p_secdrone.c): flying friendly laser drone + its shot.
    S_SECDR_STND,
    S_SECDR_RUN1,
    S_SECDR_ATK1, S_SECDR_ATK2, S_SECDR_ATK3, S_SECDR_ATK4, S_SECDR_ATK5, S_SECDR_ATK6,
    S_SECDR_PAIN,
    S_SECDR_DIE1, S_SECDR_DIE2, S_SECDR_DIE3, S_SECDR_DIE4, S_SECDR_DIE5, S_SECDR_DIE6, S_SECDR_DIE7,
    S_SECDRSHOT1, S_SECDRSHOT2,
    S_SECDRSHOT_X1, S_SECDRSHOT_X2, S_SECDRSHOT_X3, S_SECDRSHOT_X4, S_SECDRSHOT_X5,
    S_SECDR_CHG1, S_SECDR_CHG2,		// lost-soul-style ram (files/p_secdrone.c)
    // (X) Hexen poison cloud (files/hexen.c): the lingering gas from the Cleric's
    // Flechette.  18 damage-tick frames looping via A_PoisonBagCheck, then a 4-frame
    // fade-out.  Reuses mobj_t.reactiontime as the lifetime counter (crispy special1).
    S_XPCL1,  S_XPCL2,  S_XPCL3,  S_XPCL4,  S_XPCL5,  S_XPCL6,
    S_XPCL7,  S_XPCL8,  S_XPCL9,  S_XPCL10, S_XPCL11, S_XPCL12,
    S_XPCL13, S_XPCL14, S_XPCL15, S_XPCL16, S_XPCL17, S_XPCL18,
    S_XPCL_X1, S_XPCL_X2, S_XPCL_X3, S_XPCL_X4,
    // (X) Flechette's thrown poison bag (files/hexen.c): a brief fuse, then
    // A_PoisonBagInit pops the cloud above it and the bag vanishes.
    S_XPBAG1, S_XPBAG2, S_XPBAG3, S_XPBAG4,
    // (X) Flechette pickup spinning icon (files/p_inv_heretic.c).
    S_HARTI_FLECHETTE,
    // (X) Poison shroom (files/hexen.c): a destructible plant that bursts into a
    // poison cloud when killed.  Idle pulse loop, pain flinch, death -> A_PoisonBagInit.
    S_XSHRM1, S_XSHRM_P1, S_XSHRM_P2,
    S_XSHRM_X1, S_XSHRM_X2, S_XSHRM_X3, S_XSHRM_X4,
    // (H) Map-placeable Heretic item/pickup spinning-icon states (one looping
    // spawnstate each; filled by Heretic_Items_Init in files/heretic_items.c).
    S_HKEY_GREEN, S_HKEY_BLUE, S_HKEY_YELLOW,
    S_HAM_GWNDW, S_HAM_GWNDH, S_HAM_MACEW, S_HAM_MACEH,
    S_HAM_CBOWW, S_HAM_CBOWH, S_HAM_SKRDW, S_HAM_SKRDH,
    S_HAM_PHRDW, S_HAM_PHRDH, S_HAM_BLSRW, S_HAM_BLSRH,
    S_HWEP_MACE, S_HWEP_SKULLROD, S_HWEP_PHOENIXROD,
    S_HWEP_CROSSBOW, S_HWEP_GAUNTLETS, S_HWEP_BLASTER,
    S_HITEM_SHIELD1, S_HITEM_SHIELD2, S_HITEM_VIAL,
    // ---- Heretic decoration / scenery (files/heretic_deco.c) ----
    S_HPOD_WAIT1, S_HPOD_PAIN1,
    S_HPOD_DIE1, S_HPOD_DIE2, S_HPOD_DIE3, S_HPOD_DIE4,
    S_HPOD_GROW1, S_HPOD_GROW2, S_HPOD_GROW3, S_HPOD_GROW4,
    S_HPOD_GROW5, S_HPOD_GROW6, S_HPOD_GROW7, S_HPOD_GROW8,
    S_HPODGOO1, S_HPODGOO2, S_HPODGOOX,
    S_HPODGEN,
    S_HSND_WIND, S_HSND_WATERFALL,
    S_HSKH70, S_HSKH60, S_HSKH45, S_HSKH35,
    S_HDEADCORVUS,	// (H) placeable dead-player (Corvus) corpse -- heretic_deco.c
    S_HCHDL1, S_HCHDL2, S_HCHDL3,
    S_HSRTC1, S_HSRTC2, S_HSRTC3,
    S_HSMALLPILLAR,
    S_HSTGS, S_HSTGL, S_HSTCS, S_HSTCL,
    S_HFBR1, S_HFBR2, S_HFBR3, S_HFBR4, S_HFBR5, S_HFBR6, S_HFBR7, S_HFBR8,
    S_HBARREL,
    S_HBRPILLAR,
    S_HMOSS1, S_HMOSS2,
    S_HWTRCH1, S_HWTRCH2, S_HWTRCH3,
    S_HHANGCORPSE,
    S_HKGZ1, S_HKGZ2, S_HKGZ3,
    S_HKGZ_START, S_HKGZ_BLUE, S_HKGZ_GREEN, S_HKGZ_YELLOW,
    S_HVOLC1, S_HVOLC2, S_HVOLC3, S_HVOLC4, S_HVOLC5, S_HVOLC6, S_HVOLC7, S_HVOLC8, S_HVOLC9,
    S_HVOLCBALL1, S_HVOLCBALL2,
    S_HVOLCBALLX1, S_HVOLCBALLX2, S_HVOLCBALLX3, S_HVOLCBALLX4, S_HVOLCBALLX5, S_HVOLCBALLX6,
    S_HVOLCTBALL1, S_HVOLCTBALL2,
    S_HVOLCTBALLX1, S_HVOLCTBALLX2, S_HVOLCTBALLX3, S_HVOLCTBALLX4, S_HVOLCTBALLX5, S_HVOLCTBALLX6, S_HVOLCTBALLX7,
    S_HTGLITGEN1, S_HTGLITGEN2,
    S_HTGLITTER1_1, S_HTGLITTER1_2, S_HTGLITTER1_3, S_HTGLITTER1_4, S_HTGLITTER1_5,
    S_HTGLITTER2_1, S_HTGLITTER2_2, S_HTGLITTER2_3, S_HTGLITTER2_4, S_HTGLITTER2_5,
    S_HTFOG1, S_HTFOG2, S_HTFOG3, S_HTFOG4, S_HTFOG5, S_HTFOG6, S_HTFOG7,
    S_HTFOG8, S_HTFOG9, S_HTFOG10, S_HTFOG11, S_HTFOG12, S_HTFOG13,
    // ---- Heretic monster variants / bosses (files/heretic_mvar.c) ----
    S_HMUML_ATK1, S_HMUML_ATK2, S_HMUML_ATK3, S_HMUML_ATK4, S_HMUML_ATK5, S_HMUML_ATK6,
    S_HMUMV_DIE1, S_HMUMV_DIE2, S_HMUMV_DIE3, S_HMUMV_DIE4, S_HMUMV_DIE5, S_HMUMV_DIE6, S_HMUMV_DIE7, S_HMUMV_DIE8,
    S_HMUM_SOUL1, S_HMUM_SOUL2, S_HMUM_SOUL3, S_HMUM_SOUL4, S_HMUM_SOUL5, S_HMUM_SOUL6, S_HMUM_SOUL7,
    S_HMUMFX1_1, S_HMUMFX1_2, S_HMUMFX1_3, S_HMUMFX1_4,
    S_HMUMFXI1_1, S_HMUMFXI1_2, S_HMUMFXI1_3, S_HMUMFXI1_4,
    S_HKNIG_ATK1, S_HKNIG_ATK2, S_HKNIG_ATK3, S_HKNIG_ATK4, S_HKNIG_ATK5, S_HKNIG_ATK6,
    S_HREDAXE1, S_HREDAXE2, S_HREDAXEX1, S_HREDAXEX2, S_HREDAXEX3,
    S_HIMPL_MSATK1, S_HIMPL_MSATK2, S_HIMPL_MSATK3,
    S_HIMB1, S_HIMB2, S_HIMB3, S_HIMBX1, S_HIMBX2, S_HIMBX3, S_HIMBX4,
    S_HSR1_LOOK1, S_HSR1_LOOK2, S_HSR1_WALK1, S_HSR1_WALK2, S_HSR1_WALK3, S_HSR1_WALK4,
    S_HSR1_PAIN1, S_HSR1_ATK1, S_HSR1_ATK2, S_HSR1_ATK3,
    S_HSR1_DIE1, S_HSR1_DIE2, S_HSR1_DIE3, S_HSR1_DIE4, S_HSR1_DIE5, S_HSR1_DIE6, S_HSR1_DIE7, S_HSR1_DIE8, S_HSR1_DIE9,
    S_HS1FX1_1, S_HS1FX1_2, S_HS1FX1_3,
    S_HS1FXI1_1, S_HS1FXI1_2, S_HS1FXI1_3, S_HS1FXI1_4, S_HS1FXI1_5,
    // ---- (X) Hexen decoration / scenery states (files/hexen_deco.c) -- ORDER MATTERS
    //      (several action funcs index spawnstate+N: POTTERYBIT_EX, ARMORCHUNK,
    //       CORPSEBIT, TELESMOKE, FLAMELARGE, BELL_X) ----
    S_ZD_CORPSEBIT4, S_ZD_LEAF1_8, S_ZD_WINGEDSTATUE, S_ZD_ROCK1,
    S_ZD_ROCK2, S_ZD_ROCK3, S_ZD_ROCK4, S_ZD_TREEDEAD,
    S_ZD_TREE, S_ZD_TREESWAMP182, S_ZD_TREESWAMP172, S_ZD_STUMPBURNED,
    S_ZD_STUMPBARE, S_ZD_STUMPSWAMP1, S_ZD_STUMPSWAMP2, S_ZD_SHROOMLARGE1,
    S_ZD_SHROOMLARGE2, S_ZD_SHROOMLARGE3, S_ZD_SHROOMSMALL1, S_ZD_SHROOMSMALL2,
    S_ZD_SHROOMSMALL3, S_ZD_SHROOMSMALL4, S_ZD_SHROOMSMALL5, S_ZD_STALAGMITEPILLAR,
    S_ZD_STALAGMITELARGE, S_ZD_STALAGMITEMEDIUM, S_ZD_STALAGMITESMALL, S_ZD_STALACTITELARGE,
    S_ZD_STALACTITEMEDIUM, S_ZD_STALACTITESMALL, S_ZD_MOSSCEILING1, S_ZD_MOSSCEILING2,
    S_ZD_SWAMPVINE, S_ZD_CORPSEKABOB, S_ZD_CORPSESLEEPING, S_ZD_TOMBSTONERIP,
    S_ZD_TOMBSTONESHANE, S_ZD_TOMBSTONEBIGCROSS, S_ZD_TOMBSTONEBRIANR, S_ZD_TOMBSTONECROSSCIRCLE,
    S_ZD_TOMBSTONESMALLCROSS, S_ZD_TOMBSTONEBRIANP, S_ZD_CORPSEHANGING, S_ZD_GARGGREENTALL,
    S_ZD_GARGBLUETALL, S_ZD_GARGGREENSHORT, S_ZD_GARGBLUESHORT, S_ZD_GARGSTRIPETALL,
    S_ZD_GARGDKREDTALL, S_ZD_GARGREDTALL, S_ZD_GARGTANTALL, S_ZD_GARGRUSTTALL,
    S_ZD_GARGDKREDSHORT, S_ZD_GARGREDSHORT, S_ZD_GARGTANSHORT, S_ZD_GARGRUSTSHORT,
    S_ZD_BANNERTATTERED, S_ZD_TREELARGE1, S_ZD_TREELARGE2, S_ZD_TREEGNARLED1,
    S_ZD_TREEGNARLED2, S_ZD_LOG, S_ZD_STALACTITEICELARGE, S_ZD_STALACTITEICEMEDIUM,
    S_ZD_STALACTITEICESMALL, S_ZD_STALACTITEICETINY, S_ZD_STALAGMITEICELARGE, S_ZD_STALAGMITEICEMEDIUM,
    S_ZD_STALAGMITEICESMALL, S_ZD_STALAGMITEICETINY, S_ZD_ROCKBROWN1, S_ZD_ROCKBROWN2,
    S_ZD_ROCKBLACK, S_ZD_RUBBLE1, S_ZD_RUBBLE2, S_ZD_RUBBLE3,
    S_ZD_VASEPILLAR, S_ZD_CORPSELYNCHED, S_ZD_IRONMAIDEN, S_ZD_BUCKET,
    S_ZD_BARREL, S_ZD_BLOODPOOL, S_ZD_WALLTORCH_U, S_ZD_TWINEDTORCH_U,
    S_ZD_FIREBULL_U, S_ZD_CAULDRON_U, S_ZD_CHANDELIER_U, S_ZD_CHAINBIT32,
    S_ZD_CHAINBIT64, S_ZD_CHAINEND_HEART, S_ZD_CHAINEND_HOOK1, S_ZD_CHAINEND_HOOK2,
    S_ZD_CHAINEND_SPIKE, S_ZD_CHAINEND_SKULL, S_ZD_TABLESHIT1, S_ZD_TABLESHIT2,
    S_ZD_TABLESHIT3, S_ZD_TABLESHIT4, S_ZD_TABLESHIT5, S_ZD_TABLESHIT6,
    S_ZD_TABLESHIT7, S_ZD_TABLESHIT8, S_ZD_TABLESHIT9, S_ZD_TABLESHIT10,
    S_ZD_BRIDGE, S_ZD_WALLTORCH1, S_ZD_WALLTORCH2, S_ZD_WALLTORCH3,
    S_ZD_WALLTORCH4, S_ZD_WALLTORCH5, S_ZD_WALLTORCH6, S_ZD_WALLTORCH7,
    S_ZD_WALLTORCH8, S_ZD_TWINEDTORCH1, S_ZD_TWINEDTORCH2, S_ZD_TWINEDTORCH3,
    S_ZD_TWINEDTORCH4, S_ZD_TWINEDTORCH5, S_ZD_TWINEDTORCH6, S_ZD_TWINEDTORCH7,
    S_ZD_TWINEDTORCH8, S_ZD_FIREBULL1, S_ZD_FIREBULL2, S_ZD_FIREBULL3,
    S_ZD_FIREBULL4, S_ZD_FIREBULL5, S_ZD_FIREBULL6, S_ZD_FIREBULL7,
    S_ZD_CAULDRON1, S_ZD_CAULDRON2, S_ZD_CAULDRON3, S_ZD_CAULDRON4,
    S_ZD_CAULDRON5, S_ZD_CAULDRON6, S_ZD_CAULDRON7, S_ZD_BLUECANDLE1,
    S_ZD_BLUECANDLE2, S_ZD_BLUECANDLE3, S_ZD_BLUECANDLE4, S_ZD_BLUECANDLE5,
    S_ZD_BRASSTORCH1, S_ZD_BRASSTORCH2, S_ZD_BRASSTORCH3, S_ZD_BRASSTORCH4,
    S_ZD_BRASSTORCH5, S_ZD_BRASSTORCH6, S_ZD_BRASSTORCH7, S_ZD_BRASSTORCH8,
    S_ZD_BRASSTORCH9, S_ZD_BRASSTORCH10, S_ZD_BRASSTORCH11, S_ZD_BRASSTORCH12,
    S_ZD_BRASSTORCH13, S_ZD_FIRETHING1, S_ZD_FIRETHING2, S_ZD_FIRETHING3,
    S_ZD_FIRETHING4, S_ZD_FIRETHING5, S_ZD_FIRETHING6, S_ZD_FIRETHING7,
    S_ZD_FIRETHING8, S_ZD_FIRETHING9, S_ZD_CHANDELIER1, S_ZD_CHANDELIER2,
    S_ZD_CHANDELIER3, S_ZD_CANDLE1, S_ZD_CANDLE2, S_ZD_CANDLE3,
    S_ZD_TELESMOKE1, S_ZD_TELESMOKE2, S_ZD_TELESMOKE3, S_ZD_TELESMOKE4,
    S_ZD_TELESMOKE5, S_ZD_TELESMOKE6, S_ZD_TELESMOKE7, S_ZD_TELESMOKE8,
    S_ZD_TELESMOKE9, S_ZD_TELESMOKE10, S_ZD_TELESMOKE11, S_ZD_TELESMOKE12,
    S_ZD_TELESMOKE13, S_ZD_TELESMOKE14, S_ZD_TELESMOKE15, S_ZD_TELESMOKE16,
    S_ZD_TELESMOKE17, S_ZD_TELESMOKE18, S_ZD_TELESMOKE19, S_ZD_TELESMOKE20,
    S_ZD_TELESMOKE21, S_ZD_TELESMOKE22, S_ZD_TELESMOKE23, S_ZD_TELESMOKE24,
    S_ZD_TELESMOKE25, S_ZD_TELESMOKE26, S_ZD_FLAMESMALL1, S_ZD_FLAMESMALL2,
    S_ZD_FLAMESMALL3, S_ZD_FLAMESMALL4, S_ZD_FLAMESMALL5, S_ZD_FLAMELARGE1,
    S_ZD_FLAMELARGE2, S_ZD_FLAMELARGE3, S_ZD_FLAMELARGE4, S_ZD_FLAMELARGE5,
    S_ZD_FLAMELARGE6, S_ZD_FLAMELARGE7, S_ZD_FLAMELARGE8, S_ZD_FLAMELARGE9,
    S_ZD_FLAMELARGE10, S_ZD_FLAMELARGE11, S_ZD_FLAMELARGE12, S_ZD_FLAMELARGE13,
    S_ZD_FLAMELARGE14, S_ZD_FLAMELARGE15, S_ZD_FLAMELARGE16, S_ZD_LYNCHEDNOHEART,
    S_ZD_BLOODDRIP, S_ZD_BLOODDRIP_X1, S_ZD_BLOODDRIP_X2, S_ZD_BLOODDRIP_X3,
    S_ZD_BLOODDRIP_X4, S_ZD_LEAFSPAWNER, S_ZD_LEAF1_1, S_ZD_LEAF1_2,
    S_ZD_LEAF1_3, S_ZD_LEAF1_4, S_ZD_LEAF1_5, S_ZD_LEAF1_6,
    S_ZD_LEAF1_7, S_ZD_LEAF1_9, S_ZD_LEAF1_10, S_ZD_LEAF1_11,
    S_ZD_LEAF1_12, S_ZD_LEAF1_13, S_ZD_LEAF1_14, S_ZD_LEAF1_15,
    S_ZD_LEAF1_16, S_ZD_LEAF1_17, S_ZD_LEAF1_18, S_ZD_LEAF_X1,
    S_ZD_LEAF2_1, S_ZD_LEAF2_2, S_ZD_LEAF2_3, S_ZD_LEAF2_4,
    S_ZD_LEAF2_5, S_ZD_LEAF2_6, S_ZD_LEAF2_7, S_ZD_LEAF2_8,
    S_ZD_LEAF2_9, S_ZD_ROCKDEBRIS1, S_ZD_ROCKDEBRIS1_D, S_ZD_ROCKDEBRIS2,
    S_ZD_ROCKDEBRIS2_D, S_ZD_ROCKDEBRIS3, S_ZD_ROCKDEBRIS3_D, S_ZD_CORPSESITTING,
    S_ZD_CORPSESITTING_X, S_ZD_CORPSEBIT1, S_ZD_CORPSEBIT2, S_ZD_CORPSEBIT3,
    S_ZD_POTTERY_EXPLODE, S_ZD_POTTERY1, S_ZD_POTTERY2, S_ZD_POTTERY3,
    S_ZD_POTTERYBIT1, S_ZD_POTTERYBIT2, S_ZD_POTTERYBIT3, S_ZD_POTTERYBIT4,
    S_ZD_POTTERYBIT5, S_ZD_POTTERYBIT_EX0, S_ZD_POTTERYBIT_EX1, S_ZD_POTTERYBIT_EX2,
    S_ZD_POTTERYBIT_EX3, S_ZD_POTTERYBIT_EX4, S_ZD_POTTERYBIT_EX5, S_ZD_SUITOFARMOR,
    S_ZD_SUITOFARMOR_X, S_ZD_ARMORCHUNK1, S_ZD_ARMORCHUNK2, S_ZD_ARMORCHUNK3,
    S_ZD_ARMORCHUNK4, S_ZD_ARMORCHUNK5, S_ZD_ARMORCHUNK6, S_ZD_ARMORCHUNK7,
    S_ZD_ARMORCHUNK8, S_ZD_ARMORCHUNK9, S_ZD_ARMORCHUNK10, S_ZD_TREEDES1,
    S_ZD_TREEDES_D1, S_ZD_TREEDES_D2, S_ZD_TREEDES_D3, S_ZD_TREEDES_D4,
    S_ZD_TREEDES_D5, S_ZD_TREEDES_D6, S_ZD_XMASTREE, S_ZD_XMASTREE_DIE,
    S_ZD_XMASTREE_X1, S_ZD_XMASTREE_X2, S_ZD_XMASTREE_X3, S_ZD_XMASTREE_X4,
    S_ZD_XMASTREE_X5, S_ZD_XMASTREE_X6, S_ZD_XMASTREE_X7, S_ZD_XMASTREE_X8,
    S_ZD_XMASTREE_X9, S_ZD_XMASTREE_X10, S_ZD_SHRUB1, S_ZD_SHRUB1_DIE,
    S_ZD_SHRUB1_X1, S_ZD_SHRUB1_X2, S_ZD_SHRUB1_X3, S_ZD_SHRUB2,
    S_ZD_SHRUB2_DIE, S_ZD_SHRUB2_X1, S_ZD_SHRUB2_X2, S_ZD_SHRUB2_X3,
    S_ZD_SHRUB2_X4, S_ZD_BELL, S_ZD_BELL_X1, S_ZD_BELL_X2,
    S_ZD_BELL_X3, S_ZD_BELL_X4, S_ZD_BELL_X5, S_ZD_BELL_X6,
    S_ZD_BELL_X7, S_ZD_BELL_X8, S_ZD_BELL_X9, S_ZD_BELL_X10,
    S_ZD_BELL_X11, S_ZD_BELL_X12, S_ZD_BELL_X13, S_ZD_BELL_X14,
    S_ZD_BELL_X15, S_ZD_BELL_X16, S_ZD_BELL_X17, S_ZD_BELL_X18,
    S_ZD_BELL_X19, S_ZD_BELL_X20, S_ZD_BELL_X21, S_ZD_BELL_X22,
    S_ZD_BELL_X23, S_ZD_BELL_X24, S_ZD_BELL_X25, S_ZD_BELL_X26,
    S_ZD_BELL_X27, S_ZD_BELL_X28, S_ZD_BELL_X29, S_ZD_BELL_X30,
    S_ZD_BELL_X31, S_ZD_BELL_X32, S_ZD_BELL_X33, S_ZD_BELL_X34,
    S_ZD_BELL_X35, S_ZD_BELL_X36, S_ZD_BELL_X37, S_ZD_BELL_X38,
    S_ZD_BELL_X39, S_ZD_BELL_X40, S_ZD_BELL_X41, S_ZD_BELL_X42,
    S_ZD_BELL_X43, S_ZD_BELL_X44, S_ZD_BELL_X45, S_ZD_BELL_X46,
    S_ZD_BELL_X47,
    // ---- (X) Hexen item/pickup/puzzle spinning-icon states (files/hexen_items.c) ----
    S_ZMANA1, S_ZMANA2, S_ZMANA3,
    S_ZARMOR1, S_ZARMOR2, S_ZARMOR3, S_ZARMOR4,
    S_ZKEY1, S_ZKEY2, S_ZKEY3, S_ZKEY4, S_ZKEY5, S_ZKEY6,
    S_ZKEY7, S_ZKEY8, S_ZKEY9, S_ZKEYA, S_ZKEYB,
    S_ZHEALBOTTLE, S_ZHEALFLASK, S_ZINVUL, S_ZSUPERHEAL, S_ZTORCH,
    S_ZTELEPORT, S_ZTELEPORTOTHER, S_ZSPEEDBOOTS, S_ZBOOSTMANA, S_ZBOOSTARMOR,
    S_ZBLASTRADIUS, S_ZHEALRADIUS,
    S_ZPUZZSKULL, S_ZPUZZGEMBIG, S_ZPUZZGEMRED, S_ZPUZZGEMGREEN1, S_ZPUZZGEMGREEN2,
    S_ZPUZZGEMBLUE1, S_ZPUZZGEMBLUE2, S_ZPUZZBOOK1, S_ZPUZZBOOK2, S_ZPUZZSKULL2,
    S_ZPUZZFWEAPON, S_ZPUZZCWEAPON, S_ZPUZZMWEAPON,
    S_ZPUZZGEAR, S_ZPUZZGEAR2, S_ZPUZZGEAR3, S_ZPUZZGEAR4,
    S_ZFSWORD1, S_ZFSWORD2, S_ZFSWORD3,
    S_ZCHOLY1, S_ZCHOLY2, S_ZCHOLY3,
    S_ZMSTAFF1, S_ZMSTAFF2, S_ZMSTAFF3,
    // ---- (X) Hexen monster/boss states (files/hexen_mon.c) ----
    S_XDE2_LOOK1, S_XDE2_LOOK2,
    S_XDE2_CHASE1, S_XDE2_CHASE2, S_XDE2_CHASE3, S_XDE2_CHASE4,
    S_XDE2_ATK1_1, S_XDE2_ATK1_2, S_XDE2_ATK1_3,
    S_XDE2_ATK2_1, S_XDE2_ATK2_2, S_XDE2_ATK2_3,
    S_XDE2_PAIN1, S_XDE2_PAIN2,
    S_XDE2_DIE1, S_XDE2_DIE2, S_XDE2_DIE3, S_XDE2_DIE4, S_XDE2_DIE5,
    S_XDE2_DIE6, S_XDE2_DIE7, S_XDE2_DIE8, S_XDE2_DIE9,
    S_XD2F_MOVE1, S_XD2F_MOVE2, S_XD2F_MOVE3, S_XD2F_MOVE4, S_XD2F_MOVE5, S_XD2F_MOVE6,
    S_XD2F_BOOM1, S_XD2F_BOOM2, S_XD2F_BOOM3, S_XD2F_BOOM4, S_XD2F_BOOM5, S_XD2F_BOOM6,
    S_XWRTB_RISE1, S_XWRTB_RISE2, S_XWRTB_RISE3,
    S_XKRX_LOOK1,
    S_XKRX_CHASE1, S_XKRX_CHASE2, S_XKRX_CHASE3, S_XKRX_CHASE4,
    S_XKRX_CHASE5, S_XKRX_CHASE6, S_XKRX_CHASE7, S_XKRX_CHASE8,
    S_XKRX_CHASE9, S_XKRX_CHASE10, S_XKRX_CHASE11, S_XKRX_CHASE12,
    S_XKRX_CHASE13, S_XKRX_CHASE14, S_XKRX_CHASE15, S_XKRX_CHASE16,
    S_XKRX_PAIN1, S_XKRX_PAIN2,
    S_XKRX_ATK1, S_XKRX_ATK2,
    S_XKRX_MIS1, S_XKRX_MIS2, S_XKRX_MIS3,
    S_XKRX_CMD1, S_XKRX_CMD2, S_XKRX_CMD3, S_XKRX_CMD4, S_XKRX_CMD5,
    S_XKRX_DIE1, S_XKRX_DIE2, S_XKRX_DIE3, S_XKRX_DIE4, S_XKRX_DIE5,
    S_XKRX_DIE6, S_XKRX_DIE7, S_XKRX_DIE8, S_XKRX_DIE9, S_XKRX_DIE10,
    S_XKRX_DIE11, S_XKRX_DIE12, S_XKRX_DIE13, S_XKRX_DIE14,
    S_XKBOLT1, S_XKBOLT2, S_XKBOLT3, S_XKBOLT4, S_XKBOLT5, S_XKBOLT6, S_XKBOLT7,
    S_XKSP_ROAM1, S_XKSP_ROAM2,
    S_XKSP_DIE1, S_XKSP_DIE2, S_XKSP_DIE3, S_XKSP_DIE4, S_XKSP_DIE5, S_XKSP_DIE6,
    S_XSOR_SPAWN1, S_XSOR_SPAWN2,
    S_XSOR_LOOK1,
    S_XSOR_WALK1, S_XSOR_WALK2, S_XSOR_WALK3, S_XSOR_WALK4,
    S_XSOR_PAIN1, S_XSOR_PAIN2,
    S_XSOR_ATK1, S_XSOR_ATK2, S_XSOR_ATK3,
    S_XSOR_DIE1, S_XSOR_DIE2, S_XSOR_DIE3, S_XSOR_DIE4, S_XSOR_DIE5,
    S_XSOR_DIE6, S_XSOR_DIE7, S_XSOR_DIE8, S_XSOR_DIE9, S_XSOR_DIE10,
    S_XSOR_DIE11, S_XSOR_DIE12, S_XSOR_DIE13, S_XSOR_DIE14, S_XSOR_DIE15,
    S_XSOR_DIE16, S_XSOR_DIE17, S_XSOR_DIE18, S_XSOR_DIE19,
    S_XSF1_1, S_XSF1_2, S_XSF1_3, S_XSF1_4,
    S_XSF1_D1, S_XSF1_D2, S_XSF1_D3,
    S_XSF2_1, S_XSF2_2, S_XSF2_3, S_XSF2_4, S_XSF2_D1,
    S_XSF3_1, S_XSF3_2, S_XSF3_3,
    S_XSF3_EXP1, S_XSF3_EXP2, S_XSF3_EXP3, S_XSF3_EXP4, S_XSF3_EXP5,
    S_XSF4_1, S_XSF4_2, S_XSF4_3,
    S_XSF4_D1, S_XSF4_D2, S_XSF4_D3, S_XSF4_D4, S_XSF4_D5,
    // (X) Minotaur / Dark Servant + its mace ball, floor fire and exit smoke
    S_XMNT_LOOK1, S_XMNT_LOOK2,
    S_XMNT_WALK1, S_XMNT_WALK2, S_XMNT_WALK3, S_XMNT_WALK4,
    S_XMNT_ATK1_1, S_XMNT_ATK1_2, S_XMNT_ATK1_3,
    S_XMNT_ATK2_1, S_XMNT_ATK2_2, S_XMNT_ATK2_3,
    S_XMNT_ATK3_1, S_XMNT_ATK3_2, S_XMNT_ATK3_3,
    S_XMNT_PAIN1, S_XMNT_PAIN2,
    S_XMNT_DIE1, S_XMNT_DIE2, S_XMNT_DIE3, S_XMNT_DIE4, S_XMNT_DIE5,
    S_XMNT_DIE6, S_XMNT_DIE7, S_XMNT_DIE8, S_XMNT_DIE9,
    S_XMF1_MOVE1, S_XMF1_MOVE2,
    S_XMF1_BOOM1, S_XMF1_BOOM2, S_XMF1_BOOM3, S_XMF1_BOOM4, S_XMF1_BOOM5, S_XMF1_BOOM6,
    S_XMF2_MOVE1,
    S_XMF2_BOOM1, S_XMF2_BOOM2, S_XMF2_BOOM3, S_XMF2_BOOM4, S_XMF2_BOOM5,
    S_XMF3_MOVE1, S_XMF3_MOVE2, S_XMF3_MOVE3, S_XMF3_MOVE4, S_XMF3_MOVE5,
    S_XMF3_MOVE6, S_XMF3_MOVE7, S_XMF3_MOVE8, S_XMF3_MOVE9,
    S_XMNS_1, S_XMNS_2, S_XMNS_3, S_XMNS_4, S_XMNS_5, S_XMNS_6,
    S_XMNS_7, S_XMNS_8, S_XMNS_9,
    // (X) Korax's bat
    S_XBAT_1, S_XBAT_2, S_XBAT_3, S_XBAT_DIE,
    // (X) Pig -- the Hexen morph creature
    S_XPIG_LOOK1,
    S_XPIG_WALK1, S_XPIG_WALK2, S_XPIG_WALK3, S_XPIG_WALK4,
    S_XPIG_PAIN1,
    S_XPIG_ATK1, S_XPIG_ATK2,
    S_XPIG_DIE1, S_XPIG_DIE2, S_XPIG_DIE3, S_XPIG_DIE4,
    S_XPIG_DIE5, S_XPIG_DIE6, S_XPIG_DIE7, S_XPIG_DIE8,
    // (X) Fighter class boss + its Quietus bolt
    S_XFTR_LOOK1,
    S_XFTR_RUN1, S_XFTR_RUN2, S_XFTR_RUN3, S_XFTR_RUN4,
    S_XFTR_ATK1, S_XFTR_ATK2,
    S_XFTR_PAIN1, S_XFTR_PAIN2,
    S_XFTR_DIE1, S_XFTR_DIE2, S_XFTR_DIE3, S_XFTR_DIE4,
    S_XFTR_DIE5, S_XFTR_DIE6, S_XFTR_DIE7,
    S_XFSF_MOVE1, S_XFSF_MOVE2, S_XFSF_MOVE3,
    S_XFSF_BOOM1, S_XFSF_BOOM2, S_XFSF_BOOM3, S_XFSF_BOOM4, S_XFSF_BOOM5,
    // (X) Cleric class boss + its holy spirit
    S_XCLR_LOOK1,
    S_XCLR_RUN1, S_XCLR_RUN2, S_XCLR_RUN3, S_XCLR_RUN4,
    S_XCLR_ATK1, S_XCLR_ATK2, S_XCLR_ATK3,
    S_XCLR_PAIN1, S_XCLR_PAIN2,
    S_XCLR_DIE1, S_XCLR_DIE2, S_XCLR_DIE3, S_XCLR_DIE4,
    S_XCLR_DIE5, S_XCLR_DIE6, S_XCLR_DIE7, S_XCLR_DIE8, S_XCLR_DIE9,
    S_XSPI_MOVE1, S_XSPI_MOVE2, S_XSPI_MOVE3, S_XSPI_MOVE4,
    S_XSPI_BOOM1, S_XSPI_BOOM2, S_XSPI_BOOM3, S_XSPI_BOOM4, S_XSPI_BOOM5,
    // (X) Mage class boss + its Bloodscourge shot
    S_XMGE_LOOK1,
    S_XMGE_RUN1, S_XMGE_RUN2, S_XMGE_RUN3, S_XMGE_RUN4,
    S_XMGE_ATK1, S_XMGE_ATK2,
    S_XMGE_PAIN1, S_XMGE_PAIN2,
    S_XMGE_DIE1, S_XMGE_DIE2, S_XMGE_DIE3, S_XMGE_DIE4,
    S_XMGE_DIE5, S_XMGE_DIE6, S_XMGE_DIE7,
    S_XMS2_MOVE1, S_XMS2_MOVE2, S_XMS2_MOVE3, S_XMS2_MOVE4,
    S_XMS2_BOOM1, S_XMS2_BOOM2, S_XMS2_BOOM3, S_XMS2_BOOM4, S_XMS2_BOOM5,
    // (H) Heretic weapons -- PL1 staff + gold wand psprites/puffs (files/heretic_weapons.c)
    S_HWP_STAFFREADY, S_HWP_STAFFDOWN, S_HWP_STAFFUP,
    S_HWP_STAFFATK1_1, S_HWP_STAFFATK1_2, S_HWP_STAFFATK1_3,
    S_HWP_STAFFPUFF1, S_HWP_STAFFPUFF2, S_HWP_STAFFPUFF3, S_HWP_STAFFPUFF4,
    S_HWP_GWANDREADY, S_HWP_GWANDDOWN, S_HWP_GWANDUP,
    S_HWP_GWANDATK1_1, S_HWP_GWANDATK1_2, S_HWP_GWANDATK1_3, S_HWP_GWANDATK1_4,
    S_HWP_GWANDPUFF1, S_HWP_GWANDPUFF2, S_HWP_GWANDPUFF3, S_HWP_GWANDPUFF4, S_HWP_GWANDPUFF5,
    // (H) Heretic weapons phase 2-4 -- PL1 psprites + projectiles/puffs (heretic_weapons.c)
    // Crossbow (wp_shotgun)
    S_HWP_CBOWREADY1, S_HWP_CBOWREADY2, S_HWP_CBOWREADY3, S_HWP_CBOWDOWN, S_HWP_CBOWUP,
    S_HWP_CBOWATK1, S_HWP_CBOWATK2, S_HWP_CBOWATK3, S_HWP_CBOWATK4,
    S_HWP_CBOWATK5, S_HWP_CBOWATK6, S_HWP_CBOWATK7, S_HWP_CBOWATK8,
    S_HWP_CBOWFX1, S_HWP_CBOWFXI1_1, S_HWP_CBOWFXI1_2, S_HWP_CBOWFXI1_3,
    S_HWP_CBOWFX3, S_HWP_CBOWFXI3_1, S_HWP_CBOWFXI3_2, S_HWP_CBOWFXI3_3,
    // Dragon Claw / Blaster (wp_chaingun)
    S_HWP_BLSRREADY, S_HWP_BLSRDOWN, S_HWP_BLSRUP,
    S_HWP_BLSRATK1, S_HWP_BLSRATK2, S_HWP_BLSRATK3, S_HWP_BLSRATK4, S_HWP_BLSRATK5, S_HWP_BLSRATK6,
    S_HWP_BLSRPUFF1, S_HWP_BLSRPUFF2, S_HWP_BLSRPUFF3, S_HWP_BLSRPUFF4, S_HWP_BLSRPUFF5,
    // Hellstaff / Skull Rod (wp_missile)
    S_HWP_HRODREADY, S_HWP_HRODDOWN, S_HWP_HRODUP,
    S_HWP_HRODATK1, S_HWP_HRODATK2, S_HWP_HRODATK3,
    S_HWP_HRODFX1_1, S_HWP_HRODFX1_2,
    S_HWP_HRODFXI1_1, S_HWP_HRODFXI1_2, S_HWP_HRODFXI1_3, S_HWP_HRODFXI1_4, S_HWP_HRODFXI1_5, S_HWP_HRODFXI1_6,
    // Phoenix Rod (wp_plasma)
    S_HWP_PHNXREADY, S_HWP_PHNXDOWN, S_HWP_PHNXUP,
    S_HWP_PHNXATK1, S_HWP_PHNXATK2, S_HWP_PHNXATK3, S_HWP_PHNXATK4, S_HWP_PHNXATK5,
    S_HWP_PHNXFX1,
    S_HWP_PHNXFXI1, S_HWP_PHNXFXI2, S_HWP_PHNXFXI3, S_HWP_PHNXFXI4,
    S_HWP_PHNXFXI5, S_HWP_PHNXFXI6, S_HWP_PHNXFXI7, S_HWP_PHNXFXI8,
    S_HWP_PHNXPUFF1, S_HWP_PHNXPUFF2, S_HWP_PHNXPUFF3, S_HWP_PHNXPUFF4, S_HWP_PHNXPUFF5,
    // Firemace (wp_bfg)
    S_HWP_MACEREADY, S_HWP_MACEDOWN, S_HWP_MACEUP,
    S_HWP_MACEATK1, S_HWP_MACEATK2, S_HWP_MACEATK3, S_HWP_MACEATK4, S_HWP_MACEATK5,
    S_HWP_MACEATK6, S_HWP_MACEATK7, S_HWP_MACEATK8, S_HWP_MACEATK9, S_HWP_MACEATK10,
    S_HWP_MACEFX1_1, S_HWP_MACEFX1_2,
    S_HWP_MACEFXI1_1, S_HWP_MACEFXI1_2, S_HWP_MACEFXI1_3, S_HWP_MACEFXI1_4, S_HWP_MACEFXI1_5,
    // Gauntlets (wp_chainsaw)
    S_HWP_GAUNREADY, S_HWP_GAUNDOWN, S_HWP_GAUNUP,
    S_HWP_GAUNATK1, S_HWP_GAUNATK2, S_HWP_GAUNATK3, S_HWP_GAUNATK4,
    S_HWP_GAUNATK5, S_HWP_GAUNATK6, S_HWP_GAUNATK7,
    S_HWP_GAUNPUFF1, S_HWP_GAUNPUFF2, S_HWP_GAUNPUFF3, S_HWP_GAUNPUFF4,
    // Lichling (Heretic buddy special -- files/heretic_lichling.c)
    S_LICL_LOOK, S_LICL_CHASE, S_LICL_ATK1, S_LICL_ATK2, S_LICL_PAIN,
    S_LICL_DIE1, S_LICL_DIE2, S_LICL_DIE3, S_LICL_DIE4, S_LICL_DIE5, S_LICL_DIE6, S_LICL_DIE7,
    S_LICF_FLY1, S_LICF_FLY2, S_LICF_BOOM1, S_LICF_BOOM2, S_LICF_BOOM3, S_LICF_BOOM4, S_LICF_BOOM5,
    S_LICE_FLY1, S_LICE_FLY2, S_LICE_BOOM1, S_LICE_BOOM2, S_LICE_BOOM3, S_LICE_BOOM4, S_LICE_BOOM5,
    // (H) liquid-terrain splash states (files/heretic_splash.c)
    S_HSPLASH1, S_HSPLASH2, S_HSPLASH3, S_HSPLASH4, S_HSPLASHX,
    S_HSPLASHBASE1, S_HSPLASHBASE2, S_HSPLASHBASE3, S_HSPLASHBASE4, S_HSPLASHBASE5, S_HSPLASHBASE6, S_HSPLASHBASE7,
    S_HLAVASPLASH1, S_HLAVASPLASH2, S_HLAVASPLASH3, S_HLAVASPLASH4, S_HLAVASPLASH5, S_HLAVASPLASH6,
    S_HLAVASMOKE1, S_HLAVASMOKE2, S_HLAVASMOKE3, S_HLAVASMOKE4, S_HLAVASMOKE5,
    S_HSLUDGECHUNK1, S_HSLUDGECHUNK2, S_HSLUDGECHUNK3, S_HSLUDGECHUNK4, S_HSLUDGECHUNKX,
    S_HSLUDGESPLASH1, S_HSLUDGESPLASH2, S_HSLUDGESPLASH3, S_HSLUDGESPLASH4,
    // (S) Strife state reservations (see strife_states.inc, strife-ve order)
#include "strife_states.inc"
    // (S) Strife Stalker buddy special (files/strife_stalker.c).  Frame letters follow
    // the SPID sheet: J/K/L ground walk, M+N the FIRING pose Strife itself never used,
    // O..[ the death run.
    S_STLKB_LOOK, S_STLKB_CHASE1, S_STLKB_CHASE2, S_STLKB_CHASE3,
    S_STLKB_CHASE4, S_STLKB_CHASE5, S_STLKB_CHASE6,
    S_STLKB_ATK1, S_STLKB_ATK2, S_STLKB_ATK3, S_STLKB_ATK4,
    S_STLKB_PAIN,
    S_STLKB_DIE1, S_STLKB_DIE2, S_STLKB_DIE3, S_STLKB_DIE4, S_STLKB_DIE5, S_STLKB_DIE6,
    S_STLKB_DIE7, S_STLKB_DIE8, S_STLKB_DIE9, S_STLKB_DIE10, S_STLKB_DIE11, S_STLKB_DIE12,
    S_STLKB_DIE13,
    NUMSTATES
} statenum_t;


#define MAXSTATEARGS	8		// mbf21: A_* codepointer arguments per frame

typedef struct
{
  spritenum_t	sprite;
  long			frame;
  long			tics;
  // void		(*action) ();
  actionf_t			action;
  statenum_t			nextstate;
  long			misc1, misc2;
  long			args[MAXSTATEARGS];	// mbf21 codepointer args (DEH "Args1..8")
  int			flags;			// mbf21 frame flags (STATEF_SKILL5FAST, ...)
} state_t;

extern state_t	*states;
extern state_t	states_builtin[];
extern int	num_states;
extern char **sprnames;
extern char *sprnames_builtin[];
extern int num_sprites;



typedef enum {
    MT_PLAYER,
    MT_POSSESSED,
    MT_SHOTGUY,
    MT_VILE,
    MT_FIRE,
    MT_UNDEAD,
    MT_TRACER,
    MT_SMOKE,
    MT_FATSO,
    MT_FATSHOT,
    MT_CHAINGUY,
    MT_TROOP,
    MT_SERGEANT,
    MT_SHADOWS,
    MT_HEAD,
    MT_BRUISER,
    MT_BRUISERSHOT,
    MT_KNIGHT,
    MT_SKULL,
    MT_SPIDER,
    MT_BABY,
    MT_CYBORG,
    MT_PAIN,
    MT_WOLFSS,
    MT_KEEN,
    MT_BOSSBRAIN,
    MT_BOSSSPIT,
    MT_BOSSTARGET,
    MT_SPAWNSHOT,
    MT_SPAWNFIRE,
    MT_BARREL,
    MT_TROOPSHOT,
    MT_HEADSHOT,
    MT_ROCKET,
    MT_PLASMA,
    MT_BFG,
    MT_ARACHPLAZ,
    MT_PUFF,
    MT_BLOOD,
    MT_TFOG,
    MT_IFOG,
    MT_TELEPORTMAN,
    MT_EXTRABFG,
    MT_MISC0,
    MT_MISC1,
    MT_MISC2,
    MT_MISC3,
    MT_MISC4,
    MT_MISC5,
    MT_MISC6,
    MT_MISC7,
    MT_MISC8,
    MT_MISC9,
    MT_MISC10,
    MT_MISC11,
    MT_MISC12,
    MT_INV,
    MT_MISC13,
    MT_INS,
    MT_MISC14,
    MT_MISC15,
    MT_MISC16,
    MT_MEGA,
    MT_CLIP,
    MT_MISC17,
    MT_MISC18,
    MT_MISC19,
    MT_MISC20,
    MT_MISC21,
    MT_MISC22,
    MT_MISC23,
    MT_MISC24,
    MT_MISC25,
    MT_CHAINGUN,
    MT_MISC26,
    MT_MISC27,
    MT_MISC28,
    MT_SHOTGUN,
    MT_SUPERSHOTGUN,
    MT_MISC29,
    MT_MISC30,
    MT_MISC31,
    MT_MISC32,
    MT_MISC33,
    MT_MISC34,
    MT_MISC35,
    MT_MISC36,
    MT_MISC37,
    MT_MISC38,
    MT_MISC39,
    MT_MISC40,
    MT_MISC41,
    MT_MISC42,
    MT_MISC43,
    MT_MISC44,
    MT_MISC45,
    MT_MISC46,
    MT_MISC47,
    MT_MISC48,
    MT_MISC49,
    MT_MISC50,
    MT_MISC51,
    MT_MISC52,
    MT_MISC53,
    MT_MISC54,
    MT_MISC55,
    MT_MISC56,
    MT_MISC57,
    MT_MISC58,
    MT_MISC59,
    MT_MISC60,
    MT_MISC61,
    MT_MISC62,
    MT_MISC63,
    MT_MISC64,
    MT_MISC65,
    MT_MISC66,
    MT_MISC67,
    MT_MISC68,
    MT_MISC69,
    MT_MISC70,
    MT_MISC71,
    MT_MISC72,
    MT_MISC73,
    MT_MISC74,
    MT_MISC75,
    MT_MISC76,
    MT_MISC77,
    MT_MISC78,
    MT_MISC79,
    MT_MISC80,
    MT_MISC81,
    MT_MISC82,
    MT_MISC83,
    MT_MISC84,
    MT_MISC85,
    MT_MISC86,
    // === BuddyDoom appended mobjtypes RELOCATED to a high base ==================
    // Same reason as the state block above: DSDHacked WADs (Legacy of Rust numbers
    // Things up to 209) share this index space.  With our builtins sitting there, a
    // LoR "Thing N =" edit landed on OUR actor and inherited its leftover fields (the
    // deployed turret came out as a LoR lamp; LoR's own breakable lamp lost its slot).
    // Basing at 1000 leaves 137..999 empty so LoR's things get clean slots, and our
    // actors resolve by their own DoomEd numbers.  Sparse gap; dsdhacked.c copies whole.
    // --- Heretic monsters (additive; mobjinfo filled by Heretic_Init) ---
    MT_HMUMMY = 1000,	// Heretic mummy / golem
    MT_HCLINK,		// Heretic sabreclaw
    MT_HIMP,		// Heretic gargoyle
    MT_HKNIGHT,		// Heretic undead warrior (knight)
    MT_HKNIGHTAXE,	// Heretic knight's thrown axe (projectile)
    MT_HBEAST,		// Heretic weredragon (beast)
    MT_HBEASTBALL,	// weredragon fireball
    MT_HWIZARD,		// Heretic disciple (wizard)
    MT_HWIZFX,		// disciple fireball
    MT_HSNAKE,		// Heretic ophidian (snake)
    MT_HSNAKEPRO,	// ophidian projectile
    MT_HMINOTAUR,	// Heretic maulotaur (minotaur miniboss)
    MT_HMINOTAURFX,	// maulotaur mace ball
    MT_HIRONLICH,	// Heretic iron lich (boss)
    MT_HHEADFX1,	// iron lich ice ball
    MT_HWHIRLWIND,	// iron lich homing whirlwind
    MT_HDSPARIL,	// Heretic d'sparil (final boss, phase-2 sorcerer)
    MT_HDSPARILFX,	// d'sparil blue bolt
    // Freedoom DOOM2-exclusive monsters -- runtime clones of the DOOM2 actors with
    // renamed sprites (files/freedoom.c).  Projectiles first (monsters reference them).
    MT_FD_TRACER,	// revenant homing missile
    MT_FD_FATSHOT,	// mancubus fireball
    MT_FD_FIRE,		// arch-vile fire
    MT_FD_ARACHPLAZ,	// arachnotron plasma
    MT_FD_UNDEAD,	// revenant
    MT_FD_FATSO,	// mancubus
    MT_FD_VILE,		// arch-vile
    MT_FD_BABY,		// arachnotron
    MT_FD_CHAINGUY,	// chaingunner
    MT_FD_KNIGHT,	// hell knight
    MT_FD_PAIN,		// pain elemental
    MT_FD_WOLFSS,	// wolfenstein SS
    MT_FD_KEEN,		// commander keen
    MT_XETTIN,		// Hexen ettin (melee brute)
    MT_REVMARINE,	// (G) revived friendly marine (files/revmarine.c)
    MT_XCENTAUR,	// Hexen centaur (melee brute)
    MT_XSLAUGHTAUR,	// Hexen slaughtaur (melee + lobbed bolt)
    MT_XCENTAUR_FX,	// slaughtaur bolt projectile
    MT_XDEMON,		// Hexen chaos serpent (melee + fire-breath)
    MT_XDEMON_FX,	// chaos serpent fireball projectile
    MT_XFIREDEMON,	// Hexen fire demon / afrit (flying, lobs fireballs)
    MT_XFIREDEMON_FX,	// fire demon fireball projectile
    MT_XFIREDEMON_SPL1,	// afrit death splotch A (scorch mark left by the burst)
    MT_XFIREDEMON_SPL2,	// afrit death splotch B
    MT_XWRAITH,		// Hexen reiver / wraith (floating, melee + bolt)
    MT_XWRAITH_FX,	// reiver bolt projectile
    MT_XBISHOP,		// Hexen dark bishop (floating caster, melee + missile)
    MT_XBISHOP_FX,	// dark bishop missile projectile
    MT_XICEGUY,		// Hexen wendigo / ice guy (floating, ranged ice shards)
    MT_XICEGUY_FX,	// wendigo ice-shard projectile
    MT_XSTALKER,	// Hexen stalker / serpent (ambusher, melee + spit) -- liquid-only
    MT_XSTALKERBOSS,	// Hexen serpent leader (ranged boss variant) -- liquid-only
    MT_XSTALKER_FX,	// stalker spit projectile
    MT_XDRAGON,		// Hexen death wyvern / dragon (big flying ranged boss)
    MT_XDRAGON_FX,	// dragon fireball projectile
    // (H) Heretic artifact pickup actors (files/p_inv_heretic.c) -- console-give
    // only for now (doomednum -1) so their real Heretic doomednums don't collide.
    MT_HARTI_FLASK,	// Quartz Flask
    MT_HARTI_URN,	// Mystic Urn
    MT_HARTI_TOME,	// Tome of Power
    MT_HARTI_TORCH,	// Torch
    MT_HARTI_BOMB,	// Time Bomb of the Ancients (pickup)
    MT_HARTI_RING,	// Ring of Invincibility
    MT_HARTI_SHADOW,	// Shadowsphere
    MT_HARTI_CHAOS,	// Chaos Device
    MT_HFIREBOMB,	// the fusing Time Bomb actor spawned on use
    MT_HARTI_WINGS,	// Wings of Wrath (flight) pickup
    MT_HARTI_EGG,	// Morph Ovum pickup
    MT_HEGGFX,		// Morph Ovum egg projectile (morphs on impact)
    MT_CHICKEN,		// (M) generic morph creature -- the Heretic chicken (files/p_morph.c)
    MT_PUSH,		// Boom point-source pusher thing (DoomEd 5001) -- wind/current away
    MT_PULL,		// Boom point-source puller thing (DoomEd 5002) -- toward
    // (Sits inside the relocated 1000+ block above, clear of the DSDHacked thing range.)
    MT_TURRET,		// deployable auto-firing sentry turret (files/p_turret.c)
    MT_SECDRONE,	// Security Drone: buddy-spawned flying friendly laser drone (files/p_secdrone.c)
    MT_SECDRONESHOT,	// its laser projectile
    MT_XPOISONCLOUD,	// (X) Hexen poison cloud -- delayed POISON damage-over-time (files/hexen.c)
    MT_XPOISONBAG,	// (X) Flechette's thrown poison bag -- pops the cloud (files/hexen.c)
    MT_HARTI_FLECHETTE,	// (X) Flechette inventory pickup (files/p_inv_heretic.c)
    MT_XPOISONSHROOM,	// (X) Hexen poison shroom -- shootable gas plant (files/hexen.c)
    // (H) Map-placeable Heretic item/pickup actors (files/heretic_items.c) --
    // real Heretic doomednums; EFFECTS out of scope (touch handled minimally).
    MT_HAKYY,		// green key   (crispy MT_AKYY, ednum 73)
    MT_HBKYY,		// blue key    (crispy MT_BKYY, ednum 79)
    MT_HCKYY,		// yellow key  (crispy MT_CKEY, ednum 80)
    MT_HAMGWNDWIMPY,	// gold wand ammo, wimpy  (wand crystal, ednum 10)
    MT_HAMGWNDHEFTY,	// gold wand ammo, hefty  (crystal geode, ednum 12)
    MT_HAMMACEWIMPY,	// mace ammo, wimpy       (ednum 13)
    MT_HAMMACEHEFTY,	// mace ammo, hefty       (ednum 16)
    MT_HAMCBOWWIMPY,	// crossbow ammo, wimpy   (ednum 18)
    MT_HAMCBOWHEFTY,	// crossbow ammo, hefty   (ednum 19)
    MT_HAMSKRDWIMPY,	// hellstaff ammo, wimpy  (ednum 20)
    MT_HAMSKRDHEFTY,	// hellstaff ammo, hefty  (ednum 21)
    MT_HAMPHRDWIMPY,	// phoenix ammo, wimpy    (ednum 22)
    MT_HAMPHRDHEFTY,	// phoenix ammo, hefty    (ednum 23)
    MT_HAMBLSRWIMPY,	// dragon-claw ammo, wimpy (ednum 54)
    MT_HAMBLSRHEFTY,	// dragon-claw ammo, hefty (ednum 55)
    MT_HWMACE,		// firemace weapon        (crispy MT_WMACE, ednum 2002)
    MT_HWSKULLROD,	// hellstaff weapon       (crispy MT_WSKULLROD, ednum 2004)
    MT_HWPHOENIXROD,	// phoenix rod weapon     (crispy MT_WPHOENIXROD, ednum 2003)
    MT_HWCROSSBOW,	// ethereal crossbow weapon (crispy MT_MISC15, ednum 2001)
    MT_HWGAUNTLETS,	// gauntlets weapon       (crispy MT_MISC13, ednum 2005)
    MT_HWBLASTER,	// dragon claw weapon     (crispy MT_MISC14, ednum 53)
    MT_HITEMSHIELD1,	// silver shield          (crispy MT_ITEMSHIELD1, ednum 85)
    MT_HITEMSHIELD2,	// enchanted shield       (crispy MT_ITEMSHIELD2, ednum 31)
    MT_HCRYSTALVIAL,	// crystal vial / +10 HP  (crispy MT_MISC0, ednum 81)
    // (H) Heretic decoration / scenery actors (files/heretic_deco.c)
    MT_HPOD, MT_HPODGOO, MT_HPODGEN,
    MT_HSOUNDWIND, MT_HSOUNDWATERFALL,
    MT_HSKULLHANG70, MT_HSKULLHANG60, MT_HSKULLHANG45, MT_HSKULLHANG35,
    MT_HCHANDELIER, MT_HSERPTORCH, MT_HSMALLPILLAR,
    MT_HSTALAGMITESMALL, MT_HSTALAGMITELARGE, MT_HSTALACTITESMALL, MT_HSTALACTITELARGE,
    MT_HFIREBRAZIER, MT_HBARREL, MT_HBRPILLAR, MT_HMOSS1, MT_HMOSS2,
    MT_HWALLTORCH, MT_HHANGINGCORPSE,
    MT_HDEADCORVUS,	// (H) placeable dead-player (Corvus) corpse -- heretic_deco.c
    MT_HKEYGIZMOBLUE, MT_HKEYGIZMOGREEN, MT_HKEYGIZMOYELLOW, MT_HKEYGIZMOFLOAT,
    MT_HVOLCANO, MT_HVOLCANOBLAST, MT_HVOLCANOTBLAST,
    MT_HTELEGLITGEN, MT_HTELEGLITGEN2, MT_HTELEGLITTER, MT_HTELEGLITTER2,
    MT_HTFOG,
    // (H) Heretic monster variants / bosses (files/heretic_mvar.c)
    MT_HMUMMYLEADER, MT_HMUMMYGHOST, MT_HMUMMYLEADERGHOST, MT_HMUMMYSOUL, MT_HMUMMYFX1,
    MT_HKNIGHTGHOST, MT_HREDAXE,
    MT_HIMPLEADER, MT_HIMPBALL,
    MT_HSORC1, MT_HSRCRFX1,
    // ---- (X) Hexen decoration / scenery actors (files/hexen_deco.c) ----
    // NOTE: MT_XZARMORCHUNK is the FIRST of the Hexen additive block; d_main.c
    // forces doomednum=-1 from here to NUMMOBJTYPES (summon-only; no hexen_mode map path).
    MT_XZARMORCHUNK, MT_XZBANNERTATTERED, MT_XZBARREL, MT_XZBELL,
    MT_XZBLOODPOOL, MT_XZBLUECANDLE, MT_XZBRASSTORCH, MT_XZBRIDGE,
    MT_XZBUCKET, MT_XZCANDLE, MT_XZCAULDRON, MT_XZCAULDRON_U,
    MT_XZCHAINBIT32, MT_XZCHAINBIT64, MT_XZCHAINEND_HEART, MT_XZCHAINEND_HOOK1,
    MT_XZCHAINEND_HOOK2, MT_XZCHAINEND_SKULL, MT_XZCHAINEND_SPIKE, MT_XZCHANDELIER,
    MT_XZCHANDELIER_U, MT_XZCORPSEBIT, MT_XZCORPSEBLOODDRIP, MT_XZCORPSEHANGING,
    MT_XZCORPSEKABOB, MT_XZCORPSELYNCHED, MT_XZCORPSESITTING, MT_XZCORPSESLEEPING,
    MT_XZFIREBULL, MT_XZFIREBULL_U, MT_XZFIRETHING, MT_XZFLAMELARGE,
    MT_XZFLAMESMALL, MT_XZGARGBLUESHORT, MT_XZGARGBLUETALL, MT_XZGARGDKREDSHORT,
    MT_XZGARGDKREDTALL, MT_XZGARGGREENSHORT, MT_XZGARGGREENTALL, MT_XZGARGREDSHORT,
    MT_XZGARGREDTALL, MT_XZGARGRUSTSHORT, MT_XZGARGRUSTTALL, MT_XZGARGSTRIPETALL,
    MT_XZGARGTANSHORT, MT_XZGARGTANTALL, MT_XZIRONMAIDEN, MT_XZLEAF1,
    MT_XZLEAF2, MT_XZLEAFSPAWNER, MT_XZLOG, MT_XZLYNCHEDNOHEART,
    MT_XZMOSSCEILING1, MT_XZMOSSCEILING2, MT_XZPOTTERY1, MT_XZPOTTERY2,
    MT_XZPOTTERY3, MT_XZPOTTERYBIT, MT_XZROCK1, MT_XZROCK2,
    MT_XZROCK3, MT_XZROCK4, MT_XZROCKBLACK, MT_XZROCKBROWN1,
    MT_XZROCKBROWN2, MT_XZROCKDEBRIS1, MT_XZROCKDEBRIS2, MT_XZROCKDEBRIS3,
    MT_XZRUBBLE1, MT_XZRUBBLE2, MT_XZRUBBLE3, MT_XZSHROOMLARGE1,
    MT_XZSHROOMLARGE2, MT_XZSHROOMLARGE3, MT_XZSHROOMSMALL1, MT_XZSHROOMSMALL2,
    MT_XZSHROOMSMALL3, MT_XZSHROOMSMALL4, MT_XZSHROOMSMALL5, MT_XZSHRUB1,
    MT_XZSHRUB2, MT_XZSTALACTITEICELARGE, MT_XZSTALACTITEICEMEDIUM, MT_XZSTALACTITEICESMALL,
    MT_XZSTALACTITEICETINY, MT_XZSTALACTITELARGE, MT_XZSTALACTITEMEDIUM, MT_XZSTALACTITESMALL,
    MT_XZSTALAGMITEICELARGE, MT_XZSTALAGMITEICEMEDIUM, MT_XZSTALAGMITEICESMALL, MT_XZSTALAGMITEICETINY,
    MT_XZSTALAGMITELARGE, MT_XZSTALAGMITEMEDIUM, MT_XZSTALAGMITEPILLAR, MT_XZSTALAGMITESMALL,
    MT_XZSTUMPBARE, MT_XZSTUMPBURNED, MT_XZSTUMPSWAMP1, MT_XZSTUMPSWAMP2,
    MT_XZSUITOFARMOR, MT_XZSWAMPVINE, MT_XZTABLESHIT1, MT_XZTABLESHIT10,
    MT_XZTABLESHIT2, MT_XZTABLESHIT3, MT_XZTABLESHIT4, MT_XZTABLESHIT5,
    MT_XZTABLESHIT6, MT_XZTABLESHIT7, MT_XZTABLESHIT8, MT_XZTABLESHIT9,
    MT_XZTELESMOKE, MT_XZTOMBSTONEBIGCROSS, MT_XZTOMBSTONEBRIANP, MT_XZTOMBSTONEBRIANR,
    MT_XZTOMBSTONECROSSCIRCLE, MT_XZTOMBSTONERIP, MT_XZTOMBSTONESHANE, MT_XZTOMBSTONESMALLCROSS,
    MT_XZTREE, MT_XZTREEDEAD, MT_XZTREEDESTRUCTIBLE, MT_XZTREEGNARLED1,
    MT_XZTREEGNARLED2, MT_XZTREELARGE1, MT_XZTREELARGE2, MT_XZTREESWAMP172,
    MT_XZTREESWAMP182, MT_XZTWINEDTORCH, MT_XZTWINEDTORCH_U, MT_XZVASEPILLAR,
    MT_XZWALLTORCH, MT_XZWALLTORCH_U, MT_XZWINGEDSTATUE, MT_XZXMASTREE,
    // ---- (X) Hexen item/pickup/puzzle actors (files/hexen_items.c) ----
    MT_ZMANA1, MT_ZMANA2, MT_ZMANA3,
    MT_ZARMOR1, MT_ZARMOR2, MT_ZARMOR3, MT_ZARMOR4,
    MT_ZKEY1, MT_ZKEY2, MT_ZKEY3, MT_ZKEY4, MT_ZKEY5, MT_ZKEY6,
    MT_ZKEY7, MT_ZKEY8, MT_ZKEY9, MT_ZKEYA, MT_ZKEYB,
    MT_ZHEALBOTTLE, MT_ZHEALFLASK, MT_ZINVUL, MT_ZSUPERHEAL, MT_ZTORCH,
    MT_ZTELEPORT, MT_ZTELEPORTOTHER, MT_ZSPEEDBOOTS, MT_ZBOOSTMANA, MT_ZBOOSTARMOR,
    MT_ZBLASTRADIUS, MT_ZHEALRADIUS,
    MT_ZPUZZSKULL, MT_ZPUZZGEMBIG, MT_ZPUZZGEMRED,
    MT_ZPUZZGEMGREEN1, MT_ZPUZZGEMGREEN2, MT_ZPUZZGEMBLUE1, MT_ZPUZZGEMBLUE2,
    MT_ZPUZZBOOK1, MT_ZPUZZBOOK2, MT_ZPUZZSKULL2,
    MT_ZPUZZFWEAPON, MT_ZPUZZCWEAPON, MT_ZPUZZMWEAPON,
    MT_ZPUZZGEAR, MT_ZPUZZGEAR2, MT_ZPUZZGEAR3, MT_ZPUZZGEAR4,
    MT_ZFSWORD1, MT_ZFSWORD2, MT_ZFSWORD3,
    MT_ZCHOLY1, MT_ZCHOLY2, MT_ZCHOLY3,
    MT_ZMSTAFF1, MT_ZMSTAFF2, MT_ZMSTAFF3,
    // ---- (X) Hexen monster / boss actors (files/hexen_mon.c) ----
    MT_XDEMON2, MT_XDEMON2_FX, MT_XWRAITHB,
    MT_XKORAX, MT_XKORAX_BOLT, MT_XKORAX_SPIRIT,
    MT_XHERESIARCH, MT_XSORCFX1, MT_XSORCFX2, MT_XSORCFX3, MT_XSORCFX4,
    // (X) Minotaur / Dark Servant + mace ball / floor-fire mortar / floor flame / smoke
    MT_XMINOTAUR, MT_XMNTFX1, MT_XMNTFX2, MT_XMNTFX3, MT_XMNTSMOKE,
    MT_XBAT,		// (X) Korax's bat
    MT_XPIG,		// (X) pig -- the Hexen morph creature (files/p_morph.c)
    // (X) "Mash" variants: ghostly, bloodless clones that leave no corpse.  Hexen
    // ednums 100-103; they reuse their normal counterpart's states.
    MT_XETTIN_MASH, MT_XCENTAUR_MASH, MT_XDEMON_MASH, MT_XDEMON2_MASH,
    // (X) Fighter / Cleric / Mage class bosses + their 4th-weapon bolts
    MT_XFIGHTERBOSS, MT_XFSWORDFX,
    MT_XCLERICBOSS,  MT_XHOLYFX,
    MT_XMAGEBOSS,    MT_XMSTAFFFX,
    // (H) Heretic weapon puffs (files/heretic_weapons.c)
    MT_HWP_STAFFPUFF, MT_HWP_GWANDPUFF,
    // (H) Heretic weapons phase 2-4 projectiles/puffs
    MT_HWP_CBOWFX1, MT_HWP_CBOWFX3, MT_HWP_BLSRPUFF, MT_HWP_HRODFX1,
    MT_HWP_PHNXFX1, MT_HWP_PHNXPUFF, MT_HWP_MACEFX1, MT_HWP_GAUNPUFF,
    MT_LICHLING, MT_LICHFIRE, MT_LICHICE,	// Lichling + its fire/ice projectiles (files/heretic_lichling.c)
    // (H) liquid-terrain splash actors (files/heretic_splash.c)
    MT_HSPLASH, MT_HSPLASHBASE, MT_HLAVASPLASH, MT_HLAVASMOKE, MT_HSLUDGECHUNK, MT_HSLUDGESPLASH,
    // (S) Strife mobjtype reservations (see strife_mt.inc, strife-ve order)
#include "strife_mt.inc"
    MT_STALKERBUDDY,		// (S) Stalker buddy special (files/strife_stalker.c)
    NUMMOBJTYPES

} mobjtype_t;

typedef struct
{
    int	doomednum;
    int	spawnstate;
    int	spawnhealth;
    int	seestate;
    int	seesound;
    int	reactiontime;
    int	attacksound;
    int	painstate;
    int	painchance;
    int	painsound;
    int	meleestate;
    int	missilestate;
    int	deathstate;
    int	xdeathstate;
    int	deathsound;
    int	speed;
    int	radius;
    int	height;
    int	mass;
    int	damage;
    int	activesound;
    int	flags;
    int	raisestate;
    // mbf21 (all default 0/off; populated by DeHackEd + used by the MBF21 codepointers/groups)
    int	flags2;			// mbf21 thing flags (MF2_*)
    int	infighting_group;	// mbf21 infighting group
    int	projectile_group;	// mbf21 projectile group
    int	splash_group;		// mbf21 splash group
    int	altspeed;		// mbf21 fast-mode speed (-1 = use `speed`)
    int	meleerange;		// mbf21 melee range (0 = default MELEERANGE)
    int	droppeditem;		// mbf21 mobjtype dropped on death (0 = none)

} mobjinfo_t;

extern mobjinfo_t *mobjinfo;
extern mobjinfo_t mobjinfo_builtin[];
extern int num_mobjtypes;

#endif
//-----------------------------------------------------------------------------
//
// $Log:$
//
//-----------------------------------------------------------------------------
