// Emacs style mode select   -*- C -*-
//-----------------------------------------------------------------------------
//
// Copyright (C) 1993-1996 by id Software, Inc.  (fork additions, DOOM Source License)
// Strife content ported from strife-ve / crispy-doom (GPL) as a reference.
//
// DESCRIPTION:
//	Additive Strife game support (BuddyDoom fork).  See strife.h.
//
//	This is the CORE of the Strife port: the doomednum->mobjtype map
//	(P_StrifeThingType), the native-sprite remap, and the availability
//	probe.  The actual actor tables are filled by the per-category
//	installers -- strife_deco.c (scenery), strife_items.c (pickups),
//	strife_mon.c (monsters + abilities) -- exactly like the Heretic split.
//
//	Phase 1 (this file): scaffolding only -- strife_mode wiring compiles and
//	DOOM/Heretic are untouched.  The tables are populated in later phases.
//
//-----------------------------------------------------------------------------

#include "doomdef.h"
#include "doomstat.h"
#include "info.h"
#include "r_state.h"		// sprites[] -- availability probe
#include "strife.h"

extern char**		sprnames;
extern state_t*		states;
extern mobjinfo_t*	mobjinfo;

//
// Strife_Init
// Fill the reserved MT_S*/S_S* slots for the Strife core.  Phase 1: no-op; the
// per-category installers do the work once the enum ranges + reference tables land.
//
void Strife_Init (void)
{
    if (!strife_mode)
	return;
}

//
// Strife_RemapNativeSprites
// The SPR_S_* slots hold Strife's NATIVE 4-char codes (files/strife_sprnames.inc),
// which is exactly right in strife_mode -- strife1.wad is the IWAD.  Outside it,
// 21 of those codes collide with a DOOM/Heretic/Hexen sprite (PLAY, SPID, BAR1,
// TFOG, ...; docs/BUDDY_SPRITE_COLLISIONS.md).  Left alone, a Strife actor summoned
// in DOOM would render the HOST game's sprite of that name -- the Stalker would come
// out as the Spider Mastermind -- and the availability probe below would report
// "Strife art present" purely because DOOM happens to own a lump called PLAY.
//
// So when we are NOT in strife_mode, point those slots at the collision-free
// placeholders that run/ID0/strifestuff.wad ships them under.  The table is
// generated by tools/extract_strife.py alongside the pack, so the two can never
// drift.  Everything else keeps its native code (those 246 are already unique).
//
// Must run BEFORE R_Init builds sprites[] from sprnames[].
//
void Strife_RemapNativeSprites (void)
{
    static const struct { int spr; const char* ph; } placeholder[] = {
#include "strife_ph.inc"
    };
    int	i;

    if (strife_mode)
	return;				// native codes are correct; nothing to do

    for (i = 0; i < (int)(sizeof placeholder / sizeof placeholder[0]); i++)
	if (placeholder[i].spr >= 0 && placeholder[i].spr < NUMSPRITES)
	    sprnames[placeholder[i].spr] = (char*) placeholder[i].ph;
}

//
// Strife_Available
// True once strife1.wad's sprites are loaded (the player sprite has frames).
//
int Strife_Available (void)
{
    return sprites[SPR_S_PLAY].numframes > 0;
}

//
// P_StrifeThingType
// Map a Strife map-thing doomednum to a BuddyDoom mobjtype, or -1 to skip it.
// The per-category installers (strife_deco/items/mon/...) set mobjinfo[MT_S_*].doomednum
// to the real Strife editor numbers, so we just scan the reserved Strife mobjtype range
// for a match -- no central switch to keep in sync (mirrors the DOOM lookup, scoped to
// MT_S_FIELDGUARD..NUMMOBJTYPES).  doomednum 0 never matches an (unfilled) slot.
//
int P_StrifeThingType (int doomednum)
{
    int	i;

    if (doomednum <= 0)
	return -1;
    for (i = MT_S_FIELDGUARD; i < NUMMOBJTYPES; i++)
	if (mobjinfo[i].doomednum == doomednum)
	    return i;
    return -1;
}
