#!/usr/bin/env python3
# gen_sprnames.py -- extract the engine's sprite-name table (files/info.c
# sprnames_builtin[]) into tools/sprnames_reserved.h, a flat list of every 4-char
# sprite base already used by ANY game in this shared engine (DOOM / Heretic / Hexen /
# Strife / Freedoom + the fork's own buddy/drone/Lichling sprites).
#
# mybuddy uses it so a new buddy's (random) sprite base can be checked against every
# reserved base -- picking one that collides would make the engine REUSE that sprite
# slot (p_buddydef.c) and silently override the existing actor's frames.
#
# Re-run after editing sprnames_builtin[] in files/info.c:
#     python tools/gen_sprnames.py

import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INFO = os.path.join(ROOT, "files", "info.c")
OUT  = os.path.join(ROOT, "tools", "sprnames_reserved.h")

def main():
    src = open(INFO, "r", encoding="latin-1").read()
    m = re.search(r"sprnames_builtin\s*\[[^\]]*\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        sys.exit("gen_sprnames: sprnames_builtin[] not found in " + INFO)
    body = m.group(1)

    names = []
    seen = set()
    for line in body.splitlines():
        line = line.split("//", 1)[0]                 # drop line comments
        for tok in re.findall(r'"([A-Za-z0-9]{4})"', line):   # sprite bases are 4 chars
            up = tok.upper()
            if up not in seen:
                seen.add(up); names.append(up)

    if not names:
        sys.exit("gen_sprnames: no 4-char sprite names parsed")

    with open(OUT, "w", encoding="ascii", newline="\n") as f:
        f.write("// Auto-generated by tools/gen_sprnames.py from files/info.c "
                "sprnames_builtin[].\n")
        f.write("// Every sprite base already used by the engine (all games merged).  Do NOT\n")
        f.write("// edit by hand -- re-run gen_sprnames.py after changing sprnames_builtin[].\n")
        f.write("#ifndef SPRNAMES_RESERVED_H\n#define SPRNAMES_RESERVED_H\n\n")
        f.write("static const char* const RESERVED_SPRITES[] = {\n")
        for i in range(0, len(names), 10):
            row = ", ".join('"%s"' % n for n in names[i:i+10])
            f.write("    " + row + ",\n")
        f.write("};\n")
        f.write("static const int RESERVED_SPRITE_COUNT = %d;\n\n" % len(names))
        f.write("#endif // SPRNAMES_RESERVED_H\n")

    print(f"gen_sprnames: {len(names)} reserved sprite bases -> {OUT}")

if __name__ == "__main__":
    main()
