// Auto-generated by tools/gen_sprnames.py from files/info.c sprnames_builtin[].
// Every sprite base already used by the engine (all games merged).  Do NOT
// edit by hand -- re-run gen_sprnames.py after changing sprnames_builtin[].
#ifndef SPRNAMES_RESERVED_H
#define SPRNAMES_RESERVED_H

static const char* const RESERVED_SPRITES[] = {
    "TROO", "SHTG", "PUNG", "PISG", "PISF", "SHTF", "SHT2", "CHGG", "CHGF", "MISG",
    "MISF", "SAWG", "PLSG", "PLSF", "BFGG", "BFGF", "BLUD", "PUFF", "BAL1", "BAL2",
    "PLSS", "PLSE", "MISL", "BFS1", "BFE1", "BFE2", "TFOG", "IFOG", "PLAY", "POSS",
    "SPOS", "VILE", "FIRE", "FATB", "FBXP", "SKEL", "MANF", "FATT", "CPOS", "SARG",
    "HEAD", "BAL7", "BOSS", "BOS2", "SKUL", "SPID", "BSPI", "APLS", "APBX", "CYBR",
    "PAIN", "SSWV", "KEEN", "BBRN", "BOSF", "ARM1", "ARM2", "BAR1", "BEXP", "FCAN",
    "BON1", "BON2", "BKEY", "RKEY", "YKEY", "BSKU", "RSKU", "YSKU", "STIM", "MEDI",
    "SOUL", "PINV", "PSTR", "PINS", "MEGA", "SUIT", "PMAP", "PVIS", "CLIP", "AMMO",
    "ROCK", "BROK", "CELL", "CELP", "SHEL", "SBOX", "BPAK", "BFUG", "MGUN", "CSAW",
    "LAUN", "PLAS", "SHOT", "SGN2", "COLU", "SMT2", "GOR1", "POL2", "POL5", "POL4",
    "POL3", "POL1", "POL6", "GOR2", "GOR3", "GOR4", "GOR5", "SMIT", "COL1", "COL2",
    "COL3", "COL4", "CAND", "CBRA", "COL6", "TRE1", "TRE2", "ELEC", "CEYE", "FSKU",
    "COL5", "TBLU", "TGRN", "TRED", "SMBT", "SMGT", "SMRT", "HDB1", "HDB2", "HDB3",
    "HDB4", "HDB5", "HDB6", "POB1", "POB2", "BRS1", "TLMP", "TLP2", "HMUM", "HCLK",
    "HIMP", "HKNI", "HKAX", "HBEA", "HBEB", "HWIZ", "HWIB", "HSNK", "HSNB", "HMIN",
    "HMNA", "HIRO", "HIRB", "HIRX", "HSR2", "HSRB", "FSKE", "FFAT", "FVIL", "FBSP",
    "FCPO", "FBO2", "FPAI", "FSSW", "FKEE", "FFAB", "FFBX", "FMAN", "FFIR", "FAPL",
    "FAPB", "XETT", "XCEN", "XCTF", "XDEM", "XDMF", "XFDM", "XFDB", "XWRT", "XWRB",
    "XBIS", "XBPF", "XICE", "XICP", "XSSP", "XSSF", "XDRA", "XDRF", "PTN1", "SPHL",
    "PWBK", "TRCH", "FBMB", "INVU", "INVS", "ATLP", "SOAR", "EGGC", "HCHK", "TNT1",
    "MTUR", "MNDR", "SHT1", "POW1", "XSSD", "PSBG", "SHRM", "AKYY", "BKYY", "CKYY",
    "AMG1", "AMG2", "AMM1", "AMM2", "AMC1", "AMC2", "AMS1", "AMS2", "AMP1", "AMP2",
    "AMB1", "AMB2", "WMCE", "WSKL", "WPHX", "WBOW", "WGNT", "WBLS", "SHLD", "SHD2",
    "HPOD", "HAMG", "HSK1", "HSK2", "HSK3", "HSK4", "HCHD", "HSRT", "HSMP", "HSGS",
    "HSGL", "HSCS", "HSCL", "HKFR", "HBAR", "HBRP", "HMS1", "HMS2", "HWTR", "HHCO",
    "HKG1", "HKGB", "HKGG", "HKGY", "HVLC", "HVFB", "HVTF", "HXPL", "HSFF", "HTGL",
    "HTLE", "HMUF", "HKRX", "HIMB", "HSR1", "HS1B", "BARL", "BBLL", "BCKT", "BDPL",
    "BDRP", "BDSH", "BNR1", "BRTR", "ZCAN", "CDLR", "CDRN", "CHNS", "CNDL", "CPB1",
    "CPB2", "CPB3", "CPB4", "CPS1", "CPS2", "CPS3", "CPS4", "CPS5", "CPS6", "FBUL",
    "FFLG", "FFSM", "FSKL", "GAR1", "GAR2", "GAR3", "GAR4", "GAR5", "GAR6", "GAR7",
    "GAR8", "GAR9", "ICM1", "ICM2", "ICM3", "ICM4", "ICT1", "ICT2", "ICT3", "ICT4",
    "IRON", "LEF1", "LEF2", "LEF3", "LOGG", "MSH1", "MSH2", "MSH3", "MSH4", "MSH5",
    "MSH6", "MSH7", "MSH8", "MSS1", "MSS2", "PBIT", "POT1", "POT2", "POT3", "RBL1",
    "RBL2", "RBL3", "RCK1", "RCK2", "RCK3", "RCK4", "RKBK", "RKBL", "RKBS", "ZRCK",
    "SGM1", "SGM2", "SGM3", "SGMP", "SHB1", "SHB2", "SLC1", "SLC2", "SLC3", "STM1",
    "STM2", "STM3", "STM4", "STT2", "STT3", "STT4", "STT5", "STWN", "ZSUI", "SWMV",
    "TMS1", "TMS2", "TMS3", "TMS4", "TMS5", "TMS6", "TMS7", "TRDT", "ZTR1", "ZTR2",
    "TRE3", "TRE4", "TRE5", "TRE6", "TRE7", "TSMK", "TST0", "TST1", "TST2", "TST3",
    "TST4", "TST5", "TST6", "TST7", "TST8", "TST9", "TWTR", "VASE", "WLTR", "XMAS",
    "MAN1", "MAN2", "MAN3", "ARM3", "ARM4", "KEY1", "KEY2", "KEY3", "KEY4", "KEY5",
    "KEY6", "KEY7", "KEY8", "KEY9", "KEYA", "KEYB", "PTN2", "TELO", "SPED", "BMAN",
    "BRAC", "BLST", "HRAD", "ASKU", "ABGM", "AGMR", "AGMG", "AGG2", "AGMB", "AGB2",
    "ABK1", "ABK2", "ASK2", "AFWP", "ACWP", "AMWP", "AGER", "AGR2", "AGR3", "AGR4",
    "WFR1", "WFR2", "WFR3", "WCH1", "WCH2", "WCH3", "WMS1", "WMS2", "WMS3", "DEM2",
    "D2FX", "KORX", "MLFX", "SPIR", "SORC", "SBS1", "SBS2", "SBS3", "SBS4", "STFF",
    "GWND", "PUF3", "PUF2", "CRBW", "BLSR", "HROD", "PHNX", "MACE", "GAUN", "FX03",
    "FX17", "FX00", "FX04", "FX08", "FX02", "PUF1", "LICS", "LICF", "LICE", "SPSH",
    "LVAS", "SLDG",
};
static const int RESERVED_SPRITE_COUNT = 472;

#endif // SPRNAMES_RESERVED_H
